# Component that displays feedback messages to the player in a balloon-style UI element
# This component receives feedback data through signals from the FeedbackController
# and displays an appropriate message with styling based on the feedback type
class_name FeedbackBalloon
extends Control

## Enum property for the feedback type, affecting visual styling
@export_enum("positive", "negative", "neutral", "info") var feedback_type := "neutral"

## Time in seconds to display the feedback before auto-hiding
@export var display_time: float = 2.5

## Reference to the panel container UI element
@onready var panel = $PanelContainer/MarginContainer/VBoxContainer/HBoxContainer

## Reference to the label UI element for displaying the message
@onready var label = $PanelContainer/MarginContainer/VBoxContainer/HBoxContainer/Label

## Reference to the icon UI element
@onready var icon = $PanelContainer/MarginContainer/VBoxContainer/HBoxContainer/Icon

## Reference to the animation player for showing/hiding animations
@onready var animation_player = $AnimationPlayer

## Reference to the audio player for sound effects
@onready var audio_player = $AudioStreamPlayer

## Color mapping for different feedback types
var colors = {
	"positive": Color(0.2, 0.8, 0.2, 0.9),  # Green
	"negative": Color(0.9, 0.2, 0.2, 0.9),  # Red
	"neutral": Color(0.7, 0.7, 0.7, 0.9),   # Gray
	"info": Color(0.2, 0.6, 1.0, 0.9)       # Blue
}

## Icon mapping for different feedback types
var icons = {
	"positive": preload("res://icon.svg"),
	"negative": preload("res://icon.svg"),
	"neutral": preload("res://icon.svg"),
	"info": preload("res://icon.svg")
}

## Initialize the component and connect to the feedback controller signal
func _ready() -> void:
	print("[FeedbackBalloon] Ready and waiting for feedback signals.")
	_GameController.feedback_controller.feedback_generated.connect(_on_feedback_generated)

## Handler for when feedback is generated by the controller
## @param feedback_data Dictionary containing the feedback information including message and type
func _on_feedback_generated(feedback_data: Dictionary) -> void:
	print("[FeedbackBalloon] Received feedback:", feedback_data)
	#show_feedback(feedback_data.message, FeedbackConfig.FeedbackType.find_key(feedback_data.type))

## Display the feedback message with appropriate styling
## @param message The text message to display in the feedback balloon
## @param type Optional string indicating the feedback type (positive, negative, neutral, info)
func show_feedback(message: String, type: String = "neutral"):
	if label == null:
		print("FeedbackBalloon: Label node not found!")
		return

	feedback_type = type
	label.text = message
	panel.modulate = colors.get(type, colors["neutral"])

	# Sonido opcional
	if audio_player and audio_player.stream:
		audio_player.play()

	# Hacer el panel invisible antes de empezar la animación
	panel.modulate.a = 0.0

	# Creamos un tween para el fade-in
	var tween := create_tween()
	tween.tween_property(panel, "modulate:a", 1.0, 0.25) # 250 ms de entrada
	await tween.finished

	# Espera el tiempo configurado
	await get_tree().create_timer(display_time).timeout

	# Creamos otro tween para el fade-out
	var tween_out := create_tween()
	tween_out.tween_property(panel, "modulate:a", 0.0, 0.25) # 250 ms de salida
	await tween_out.finished

	queue_free()
