/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  SingleUserResponse,
  UserChangePassword,
  UserCreate,
  UserLogin,
  UserLoginResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SingleUserResponseFromJSON,
    SingleUserResponseToJSON,
    UserChangePasswordFromJSON,
    UserChangePasswordToJSON,
    UserCreateFromJSON,
    UserCreateToJSON,
    UserLoginFromJSON,
    UserLoginToJSON,
    UserLoginResponseFromJSON,
    UserLoginResponseToJSON,
} from '../models/index';

export interface ChangePasswordApiV1AuthChangePasswordPostRequest {
    userId: number;
    userChangePassword: UserChangePassword;
}

export interface LoginForAccessTokenApiV1AuthLoginPostRequest {
    userLogin: UserLogin;
}

export interface RegisterUserApiV1AuthRegisterPostRequest {
    userCreate: UserCreate;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Creates request options for changePasswordApiV1AuthChangePasswordPost without sending the request
     */
    async changePasswordApiV1AuthChangePasswordPostRequestOpts(requestParameters: ChangePasswordApiV1AuthChangePasswordPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling changePasswordApiV1AuthChangePasswordPost().'
            );
        }

        if (requestParameters['userChangePassword'] == null) {
            throw new runtime.RequiredError(
                'userChangePassword',
                'Required parameter "userChangePassword" was null or undefined when calling changePasswordApiV1AuthChangePasswordPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/change-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserChangePasswordToJSON(requestParameters['userChangePassword']),
        };
    }

    /**
     * Cambia la contraseña de un usuario.  - **user_id**: ID del usuario (en query parameter o body) - **current_password**: Contraseña actual para verificación - **new_password**: Nueva contraseña (mínimo 8 caracteres)
     * Change Password
     */
    async changePasswordApiV1AuthChangePasswordPostRaw(requestParameters: ChangePasswordApiV1AuthChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SingleUserResponse>> {
        const requestOptions = await this.changePasswordApiV1AuthChangePasswordPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SingleUserResponseFromJSON(jsonValue));
    }

    /**
     * Cambia la contraseña de un usuario.  - **user_id**: ID del usuario (en query parameter o body) - **current_password**: Contraseña actual para verificación - **new_password**: Nueva contraseña (mínimo 8 caracteres)
     * Change Password
     */
    async changePasswordApiV1AuthChangePasswordPost(requestParameters: ChangePasswordApiV1AuthChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SingleUserResponse> {
        const response = await this.changePasswordApiV1AuthChangePasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginForAccessTokenApiV1AuthLoginPost without sending the request
     */
    async loginForAccessTokenApiV1AuthLoginPostRequestOpts(requestParameters: LoginForAccessTokenApiV1AuthLoginPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userLogin'] == null) {
            throw new runtime.RequiredError(
                'userLogin',
                'Required parameter "userLogin" was null or undefined when calling loginForAccessTokenApiV1AuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserLoginToJSON(requestParameters['userLogin']),
        };
    }

    /**
     * Autentica un usuario y retorna el token de acceso JWT.  - **username**: Username del usuario (opcional) - **email**: Email del usuario (opcional) - **password**: Contraseña del usuario  Nota: Proporcionar username O email, no ambos requeridos.  Retorna el token JWT y los datos del usuario autenticado.
     * Login For Access Token
     */
    async loginForAccessTokenApiV1AuthLoginPostRaw(requestParameters: LoginForAccessTokenApiV1AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserLoginResponse>> {
        const requestOptions = await this.loginForAccessTokenApiV1AuthLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserLoginResponseFromJSON(jsonValue));
    }

    /**
     * Autentica un usuario y retorna el token de acceso JWT.  - **username**: Username del usuario (opcional) - **email**: Email del usuario (opcional) - **password**: Contraseña del usuario  Nota: Proporcionar username O email, no ambos requeridos.  Retorna el token JWT y los datos del usuario autenticado.
     * Login For Access Token
     */
    async loginForAccessTokenApiV1AuthLoginPost(requestParameters: LoginForAccessTokenApiV1AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserLoginResponse> {
        const response = await this.loginForAccessTokenApiV1AuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerUserApiV1AuthRegisterPost without sending the request
     */
    async registerUserApiV1AuthRegisterPostRequestOpts(requestParameters: RegisterUserApiV1AuthRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userCreate'] == null) {
            throw new runtime.RequiredError(
                'userCreate',
                'Required parameter "userCreate" was null or undefined when calling registerUserApiV1AuthRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserCreateToJSON(requestParameters['userCreate']),
        };
    }

    /**
     * Registra un nuevo usuario y retorna el token de acceso JWT.  - **username**: Nombre de usuario (debe ser único) - **email**: Email del usuario (debe ser único) - **name**: Nombre del usuario (requerido) - **lastname**: Apellido del usuario (opcional) - **password**: Contraseña del usuario (será hasheada)  Retorna el token JWT y los datos del usuario creado.
     * Register User
     */
    async registerUserApiV1AuthRegisterPostRaw(requestParameters: RegisterUserApiV1AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserLoginResponse>> {
        const requestOptions = await this.registerUserApiV1AuthRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserLoginResponseFromJSON(jsonValue));
    }

    /**
     * Registra un nuevo usuario y retorna el token de acceso JWT.  - **username**: Nombre de usuario (debe ser único) - **email**: Email del usuario (debe ser único) - **name**: Nombre del usuario (requerido) - **lastname**: Apellido del usuario (opcional) - **password**: Contraseña del usuario (será hasheada)  Retorna el token JWT y los datos del usuario creado.
     * Register User
     */
    async registerUserApiV1AuthRegisterPost(requestParameters: RegisterUserApiV1AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserLoginResponse> {
        const response = await this.registerUserApiV1AuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
