/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GameCreate,
  GameCreateResponse,
  GameDeleteResponse,
  GameInstanceCreate,
  GameInstanceCreateResponse,
  GameInstanceEnd,
  GameInstanceEndResponse,
  GameInstanceListResponse,
  GameListResponse,
  GameUpdate,
  GameUpdateResponse,
  HTTPValidationError,
  LevelCreate,
  LevelCreateResponse,
  LevelDeleteResponse,
  LevelListResponse,
  LevelUpdate,
  LevelUpdateResponse,
  SegmentLevelCreate,
  SegmentLevelCreateResponse,
  SegmentLevelDeleteResponse,
  SegmentLevelListResponse,
  SegmentLevelUpdate,
  SegmentLevelUpdateResponse,
  SingleGameInstanceResponse,
  SingleGameResponse,
  SingleLevelResponse,
} from '../models/index';
import {
    GameCreateFromJSON,
    GameCreateToJSON,
    GameCreateResponseFromJSON,
    GameCreateResponseToJSON,
    GameDeleteResponseFromJSON,
    GameDeleteResponseToJSON,
    GameInstanceCreateFromJSON,
    GameInstanceCreateToJSON,
    GameInstanceCreateResponseFromJSON,
    GameInstanceCreateResponseToJSON,
    GameInstanceEndFromJSON,
    GameInstanceEndToJSON,
    GameInstanceEndResponseFromJSON,
    GameInstanceEndResponseToJSON,
    GameInstanceListResponseFromJSON,
    GameInstanceListResponseToJSON,
    GameListResponseFromJSON,
    GameListResponseToJSON,
    GameUpdateFromJSON,
    GameUpdateToJSON,
    GameUpdateResponseFromJSON,
    GameUpdateResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LevelCreateFromJSON,
    LevelCreateToJSON,
    LevelCreateResponseFromJSON,
    LevelCreateResponseToJSON,
    LevelDeleteResponseFromJSON,
    LevelDeleteResponseToJSON,
    LevelListResponseFromJSON,
    LevelListResponseToJSON,
    LevelUpdateFromJSON,
    LevelUpdateToJSON,
    LevelUpdateResponseFromJSON,
    LevelUpdateResponseToJSON,
    SegmentLevelCreateFromJSON,
    SegmentLevelCreateToJSON,
    SegmentLevelCreateResponseFromJSON,
    SegmentLevelCreateResponseToJSON,
    SegmentLevelDeleteResponseFromJSON,
    SegmentLevelDeleteResponseToJSON,
    SegmentLevelListResponseFromJSON,
    SegmentLevelListResponseToJSON,
    SegmentLevelUpdateFromJSON,
    SegmentLevelUpdateToJSON,
    SegmentLevelUpdateResponseFromJSON,
    SegmentLevelUpdateResponseToJSON,
    SingleGameInstanceResponseFromJSON,
    SingleGameInstanceResponseToJSON,
    SingleGameResponseFromJSON,
    SingleGameResponseToJSON,
    SingleLevelResponseFromJSON,
    SingleLevelResponseToJSON,
} from '../models/index';

export interface CreateGameApiV1GamesPostRequest {
    gameCreate: GameCreate;
}

export interface CreateGameInstanceApiV1GameInstancesGameIdInstancesPostRequest {
    gameId: number;
    gameInstanceCreate: GameInstanceCreate;
}

export interface CreateGameLevelApiV1GamesGameIdLevelsPostRequest {
    gameId: number;
    levelCreate: LevelCreate;
}

export interface CreateLevelSegmentApiV1SegmentsLevelIdSegmentsPostRequest {
    levelId: number;
    segmentLevelCreate: SegmentLevelCreate;
}

export interface DeleteGameApiV1GamesGameIdDeleteRequest {
    gameId: number;
}

export interface DeleteLevelApiV1LevelsLevelIdDeleteRequest {
    levelId: number;
}

export interface DeleteSegmentApiV1SegmentsSegmentIdDeleteRequest {
    segmentId: number;
}

export interface EndInstanceApiV1GameInstancesInstanceIdEndPutRequest {
    instanceId: number;
    gameInstanceEnd?: GameInstanceEnd;
}

export interface GetGameApiV1GamesGameIdGetRequest {
    gameId: number;
}

export interface GetGameLevelsApiV1GamesGameIdLevelsGetRequest {
    gameId: number;
    skip?: number;
    limit?: number;
}

export interface GetGamesApiV1GamesGetRequest {
    skip?: number;
    limit?: number;
}

export interface GetInstanceApiV1GameInstancesInstanceIdGetRequest {
    instanceId: number;
}

export interface GetLevelApiV1LevelsLevelIdGetRequest {
    levelId: number;
}

export interface GetLevelSegmentsApiV1SegmentsLevelIdSegmentsGetRequest {
    levelId: number;
    skip?: number;
    limit?: number;
}

export interface ListGameInstancesApiV1GameInstancesGameIdInstancesGetRequest {
    gameId: number;
    skip?: number;
    limit?: number;
    statusFilter?: string;
}

export interface UpdateGameApiV1GamesGameIdPutRequest {
    gameId: number;
    gameUpdate: GameUpdate;
}

export interface UpdateLevelApiV1LevelsLevelIdPutRequest {
    levelId: number;
    levelUpdate: LevelUpdate;
}

export interface UpdateSegmentApiV1SegmentsSegmentIdPutRequest {
    segmentId: number;
    segmentLevelUpdate: SegmentLevelUpdate;
}

/**
 * 
 */
export class GamesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createGameApiV1GamesPost without sending the request
     */
    async createGameApiV1GamesPostRequestOpts(requestParameters: CreateGameApiV1GamesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['gameCreate'] == null) {
            throw new runtime.RequiredError(
                'gameCreate',
                'Required parameter "gameCreate" was null or undefined when calling createGameApiV1GamesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/games`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GameCreateToJSON(requestParameters['gameCreate']),
        };
    }

    /**
     * Crea un nuevo juego.  - **title**: Título del juego (requerido) - **description**: Descripción del juego (opcional) - **creator**: Creador del juego (opcional) - **subject**: Materia/asignatura (opcional) - **publication_status**: Estado de publicación (opcional)
     * Create Game
     */
    async createGameApiV1GamesPostRaw(requestParameters: CreateGameApiV1GamesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameCreateResponse>> {
        const requestOptions = await this.createGameApiV1GamesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameCreateResponseFromJSON(jsonValue));
    }

    /**
     * Crea un nuevo juego.  - **title**: Título del juego (requerido) - **description**: Descripción del juego (opcional) - **creator**: Creador del juego (opcional) - **subject**: Materia/asignatura (opcional) - **publication_status**: Estado de publicación (opcional)
     * Create Game
     */
    async createGameApiV1GamesPost(requestParameters: CreateGameApiV1GamesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameCreateResponse> {
        const response = await this.createGameApiV1GamesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createGameInstanceApiV1GameInstancesGameIdInstancesPost without sending the request
     */
    async createGameInstanceApiV1GameInstancesGameIdInstancesPostRequestOpts(requestParameters: CreateGameInstanceApiV1GameInstancesGameIdInstancesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['gameId'] == null) {
            throw new runtime.RequiredError(
                'gameId',
                'Required parameter "gameId" was null or undefined when calling createGameInstanceApiV1GameInstancesGameIdInstancesPost().'
            );
        }

        if (requestParameters['gameInstanceCreate'] == null) {
            throw new runtime.RequiredError(
                'gameInstanceCreate',
                'Required parameter "gameInstanceCreate" was null or undefined when calling createGameInstanceApiV1GameInstancesGameIdInstancesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/game-instances/{game_id}/instances`;
        urlPath = urlPath.replace(`{${"game_id"}}`, encodeURIComponent(String(requestParameters['gameId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GameInstanceCreateToJSON(requestParameters['gameInstanceCreate']),
        };
    }

    /**
     * Crea una nueva instancia de juego para un estudiante.  - **game_id**: ID del juego - **student_id**: ID del estudiante (requerido) - **status**: Estado inicial (default: active)
     * Create Game Instance
     */
    async createGameInstanceApiV1GameInstancesGameIdInstancesPostRaw(requestParameters: CreateGameInstanceApiV1GameInstancesGameIdInstancesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameInstanceCreateResponse>> {
        const requestOptions = await this.createGameInstanceApiV1GameInstancesGameIdInstancesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameInstanceCreateResponseFromJSON(jsonValue));
    }

    /**
     * Crea una nueva instancia de juego para un estudiante.  - **game_id**: ID del juego - **student_id**: ID del estudiante (requerido) - **status**: Estado inicial (default: active)
     * Create Game Instance
     */
    async createGameInstanceApiV1GameInstancesGameIdInstancesPost(requestParameters: CreateGameInstanceApiV1GameInstancesGameIdInstancesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameInstanceCreateResponse> {
        const response = await this.createGameInstanceApiV1GameInstancesGameIdInstancesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createGameLevelApiV1GamesGameIdLevelsPost without sending the request
     */
    async createGameLevelApiV1GamesGameIdLevelsPostRequestOpts(requestParameters: CreateGameLevelApiV1GamesGameIdLevelsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['gameId'] == null) {
            throw new runtime.RequiredError(
                'gameId',
                'Required parameter "gameId" was null or undefined when calling createGameLevelApiV1GamesGameIdLevelsPost().'
            );
        }

        if (requestParameters['levelCreate'] == null) {
            throw new runtime.RequiredError(
                'levelCreate',
                'Required parameter "levelCreate" was null or undefined when calling createGameLevelApiV1GamesGameIdLevelsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/games/{game_id}/levels`;
        urlPath = urlPath.replace(`{${"game_id"}}`, encodeURIComponent(String(requestParameters['gameId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LevelCreateToJSON(requestParameters['levelCreate']),
        };
    }

    /**
     * Crea un nuevo nivel en un juego.  - **game_id**: ID del juego - **level_number**: Número del nivel (requerido) - **title**: Título del nivel (requerido) - **description**: Descripción del nivel (opcional) - **goal**: Objetivo del nivel (opcional)
     * Create Game Level
     */
    async createGameLevelApiV1GamesGameIdLevelsPostRaw(requestParameters: CreateGameLevelApiV1GamesGameIdLevelsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LevelCreateResponse>> {
        const requestOptions = await this.createGameLevelApiV1GamesGameIdLevelsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LevelCreateResponseFromJSON(jsonValue));
    }

    /**
     * Crea un nuevo nivel en un juego.  - **game_id**: ID del juego - **level_number**: Número del nivel (requerido) - **title**: Título del nivel (requerido) - **description**: Descripción del nivel (opcional) - **goal**: Objetivo del nivel (opcional)
     * Create Game Level
     */
    async createGameLevelApiV1GamesGameIdLevelsPost(requestParameters: CreateGameLevelApiV1GamesGameIdLevelsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LevelCreateResponse> {
        const response = await this.createGameLevelApiV1GamesGameIdLevelsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createLevelSegmentApiV1SegmentsLevelIdSegmentsPost without sending the request
     */
    async createLevelSegmentApiV1SegmentsLevelIdSegmentsPostRequestOpts(requestParameters: CreateLevelSegmentApiV1SegmentsLevelIdSegmentsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['levelId'] == null) {
            throw new runtime.RequiredError(
                'levelId',
                'Required parameter "levelId" was null or undefined when calling createLevelSegmentApiV1SegmentsLevelIdSegmentsPost().'
            );
        }

        if (requestParameters['segmentLevelCreate'] == null) {
            throw new runtime.RequiredError(
                'segmentLevelCreate',
                'Required parameter "segmentLevelCreate" was null or undefined when calling createLevelSegmentApiV1SegmentsLevelIdSegmentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/segments/{level_id}/segments`;
        urlPath = urlPath.replace(`{${"level_id"}}`, encodeURIComponent(String(requestParameters['levelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SegmentLevelCreateToJSON(requestParameters['segmentLevelCreate']),
        };
    }

    /**
     * Crea un nuevo segmento en un nivel.  - **level_id**: ID del nivel - **configuration**: Configuración JSON del segmento (opcional)
     * Create Level Segment
     */
    async createLevelSegmentApiV1SegmentsLevelIdSegmentsPostRaw(requestParameters: CreateLevelSegmentApiV1SegmentsLevelIdSegmentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SegmentLevelCreateResponse>> {
        const requestOptions = await this.createLevelSegmentApiV1SegmentsLevelIdSegmentsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SegmentLevelCreateResponseFromJSON(jsonValue));
    }

    /**
     * Crea un nuevo segmento en un nivel.  - **level_id**: ID del nivel - **configuration**: Configuración JSON del segmento (opcional)
     * Create Level Segment
     */
    async createLevelSegmentApiV1SegmentsLevelIdSegmentsPost(requestParameters: CreateLevelSegmentApiV1SegmentsLevelIdSegmentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SegmentLevelCreateResponse> {
        const response = await this.createLevelSegmentApiV1SegmentsLevelIdSegmentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteGameApiV1GamesGameIdDelete without sending the request
     */
    async deleteGameApiV1GamesGameIdDeleteRequestOpts(requestParameters: DeleteGameApiV1GamesGameIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['gameId'] == null) {
            throw new runtime.RequiredError(
                'gameId',
                'Required parameter "gameId" was null or undefined when calling deleteGameApiV1GamesGameIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/games/{game_id}`;
        urlPath = urlPath.replace(`{${"game_id"}}`, encodeURIComponent(String(requestParameters['gameId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Elimina un juego (soft delete).  - **game_id**: ID del juego a eliminar
     * Delete Game
     */
    async deleteGameApiV1GamesGameIdDeleteRaw(requestParameters: DeleteGameApiV1GamesGameIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameDeleteResponse>> {
        const requestOptions = await this.deleteGameApiV1GamesGameIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameDeleteResponseFromJSON(jsonValue));
    }

    /**
     * Elimina un juego (soft delete).  - **game_id**: ID del juego a eliminar
     * Delete Game
     */
    async deleteGameApiV1GamesGameIdDelete(requestParameters: DeleteGameApiV1GamesGameIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameDeleteResponse> {
        const response = await this.deleteGameApiV1GamesGameIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteLevelApiV1LevelsLevelIdDelete without sending the request
     */
    async deleteLevelApiV1LevelsLevelIdDeleteRequestOpts(requestParameters: DeleteLevelApiV1LevelsLevelIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['levelId'] == null) {
            throw new runtime.RequiredError(
                'levelId',
                'Required parameter "levelId" was null or undefined when calling deleteLevelApiV1LevelsLevelIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/levels/{level_id}`;
        urlPath = urlPath.replace(`{${"level_id"}}`, encodeURIComponent(String(requestParameters['levelId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Elimina un nivel (soft delete).  - **level_id**: ID del nivel a eliminar
     * Delete Level
     */
    async deleteLevelApiV1LevelsLevelIdDeleteRaw(requestParameters: DeleteLevelApiV1LevelsLevelIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LevelDeleteResponse>> {
        const requestOptions = await this.deleteLevelApiV1LevelsLevelIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LevelDeleteResponseFromJSON(jsonValue));
    }

    /**
     * Elimina un nivel (soft delete).  - **level_id**: ID del nivel a eliminar
     * Delete Level
     */
    async deleteLevelApiV1LevelsLevelIdDelete(requestParameters: DeleteLevelApiV1LevelsLevelIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LevelDeleteResponse> {
        const response = await this.deleteLevelApiV1LevelsLevelIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSegmentApiV1SegmentsSegmentIdDelete without sending the request
     */
    async deleteSegmentApiV1SegmentsSegmentIdDeleteRequestOpts(requestParameters: DeleteSegmentApiV1SegmentsSegmentIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['segmentId'] == null) {
            throw new runtime.RequiredError(
                'segmentId',
                'Required parameter "segmentId" was null or undefined when calling deleteSegmentApiV1SegmentsSegmentIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/segments/{segment_id}`;
        urlPath = urlPath.replace(`{${"segment_id"}}`, encodeURIComponent(String(requestParameters['segmentId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Elimina un segmento (soft delete).  - **segment_id**: ID del segmento a eliminar
     * Delete Segment
     */
    async deleteSegmentApiV1SegmentsSegmentIdDeleteRaw(requestParameters: DeleteSegmentApiV1SegmentsSegmentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SegmentLevelDeleteResponse>> {
        const requestOptions = await this.deleteSegmentApiV1SegmentsSegmentIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SegmentLevelDeleteResponseFromJSON(jsonValue));
    }

    /**
     * Elimina un segmento (soft delete).  - **segment_id**: ID del segmento a eliminar
     * Delete Segment
     */
    async deleteSegmentApiV1SegmentsSegmentIdDelete(requestParameters: DeleteSegmentApiV1SegmentsSegmentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SegmentLevelDeleteResponse> {
        const response = await this.deleteSegmentApiV1SegmentsSegmentIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for endInstanceApiV1GameInstancesInstanceIdEndPut without sending the request
     */
    async endInstanceApiV1GameInstancesInstanceIdEndPutRequestOpts(requestParameters: EndInstanceApiV1GameInstancesInstanceIdEndPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['instanceId'] == null) {
            throw new runtime.RequiredError(
                'instanceId',
                'Required parameter "instanceId" was null or undefined when calling endInstanceApiV1GameInstancesInstanceIdEndPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/game-instances/{instance_id}/end`;
        urlPath = urlPath.replace(`{${"instance_id"}}`, encodeURIComponent(String(requestParameters['instanceId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: GameInstanceEndToJSON(requestParameters['gameInstanceEnd']),
        };
    }

    /**
     * Finaliza una instancia de juego.  - **instance_id**: ID de la instancia a finalizar - **status**: Estado final (default: completed)
     * End Instance
     */
    async endInstanceApiV1GameInstancesInstanceIdEndPutRaw(requestParameters: EndInstanceApiV1GameInstancesInstanceIdEndPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameInstanceEndResponse>> {
        const requestOptions = await this.endInstanceApiV1GameInstancesInstanceIdEndPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameInstanceEndResponseFromJSON(jsonValue));
    }

    /**
     * Finaliza una instancia de juego.  - **instance_id**: ID de la instancia a finalizar - **status**: Estado final (default: completed)
     * End Instance
     */
    async endInstanceApiV1GameInstancesInstanceIdEndPut(requestParameters: EndInstanceApiV1GameInstancesInstanceIdEndPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameInstanceEndResponse> {
        const response = await this.endInstanceApiV1GameInstancesInstanceIdEndPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGameApiV1GamesGameIdGet without sending the request
     */
    async getGameApiV1GamesGameIdGetRequestOpts(requestParameters: GetGameApiV1GamesGameIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['gameId'] == null) {
            throw new runtime.RequiredError(
                'gameId',
                'Required parameter "gameId" was null or undefined when calling getGameApiV1GamesGameIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/games/{game_id}`;
        urlPath = urlPath.replace(`{${"game_id"}}`, encodeURIComponent(String(requestParameters['gameId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene los detalles de un juego específico.  - **game_id**: ID del juego a obtener
     * Get Game
     */
    async getGameApiV1GamesGameIdGetRaw(requestParameters: GetGameApiV1GamesGameIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SingleGameResponse>> {
        const requestOptions = await this.getGameApiV1GamesGameIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SingleGameResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene los detalles de un juego específico.  - **game_id**: ID del juego a obtener
     * Get Game
     */
    async getGameApiV1GamesGameIdGet(requestParameters: GetGameApiV1GamesGameIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SingleGameResponse> {
        const response = await this.getGameApiV1GamesGameIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGameLevelsApiV1GamesGameIdLevelsGet without sending the request
     */
    async getGameLevelsApiV1GamesGameIdLevelsGetRequestOpts(requestParameters: GetGameLevelsApiV1GamesGameIdLevelsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['gameId'] == null) {
            throw new runtime.RequiredError(
                'gameId',
                'Required parameter "gameId" was null or undefined when calling getGameLevelsApiV1GamesGameIdLevelsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/games/{game_id}/levels`;
        urlPath = urlPath.replace(`{${"game_id"}}`, encodeURIComponent(String(requestParameters['gameId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lista los niveles de un juego con paginación.  - **game_id**: ID del juego - **skip**: Número de registros a saltar - **limit**: Número máximo de registros a devolver
     * Get Game Levels
     */
    async getGameLevelsApiV1GamesGameIdLevelsGetRaw(requestParameters: GetGameLevelsApiV1GamesGameIdLevelsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LevelListResponse>> {
        const requestOptions = await this.getGameLevelsApiV1GamesGameIdLevelsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LevelListResponseFromJSON(jsonValue));
    }

    /**
     * Lista los niveles de un juego con paginación.  - **game_id**: ID del juego - **skip**: Número de registros a saltar - **limit**: Número máximo de registros a devolver
     * Get Game Levels
     */
    async getGameLevelsApiV1GamesGameIdLevelsGet(requestParameters: GetGameLevelsApiV1GamesGameIdLevelsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LevelListResponse> {
        const response = await this.getGameLevelsApiV1GamesGameIdLevelsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGamesApiV1GamesGet without sending the request
     */
    async getGamesApiV1GamesGetRequestOpts(requestParameters: GetGamesApiV1GamesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/games`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lista todos los juegos con paginación.  - **skip**: Número de registros a saltar (para paginación) - **limit**: Número máximo de registros a devolver (1-100)
     * Get Games
     */
    async getGamesApiV1GamesGetRaw(requestParameters: GetGamesApiV1GamesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameListResponse>> {
        const requestOptions = await this.getGamesApiV1GamesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameListResponseFromJSON(jsonValue));
    }

    /**
     * Lista todos los juegos con paginación.  - **skip**: Número de registros a saltar (para paginación) - **limit**: Número máximo de registros a devolver (1-100)
     * Get Games
     */
    async getGamesApiV1GamesGet(requestParameters: GetGamesApiV1GamesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameListResponse> {
        const response = await this.getGamesApiV1GamesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getInstanceApiV1GameInstancesInstanceIdGet without sending the request
     */
    async getInstanceApiV1GameInstancesInstanceIdGetRequestOpts(requestParameters: GetInstanceApiV1GameInstancesInstanceIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['instanceId'] == null) {
            throw new runtime.RequiredError(
                'instanceId',
                'Required parameter "instanceId" was null or undefined when calling getInstanceApiV1GameInstancesInstanceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/game-instances/{instance_id}`;
        urlPath = urlPath.replace(`{${"instance_id"}}`, encodeURIComponent(String(requestParameters['instanceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene los detalles de una instancia de juego.  - **instance_id**: ID de la instancia
     * Get Instance
     */
    async getInstanceApiV1GameInstancesInstanceIdGetRaw(requestParameters: GetInstanceApiV1GameInstancesInstanceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SingleGameInstanceResponse>> {
        const requestOptions = await this.getInstanceApiV1GameInstancesInstanceIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SingleGameInstanceResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene los detalles de una instancia de juego.  - **instance_id**: ID de la instancia
     * Get Instance
     */
    async getInstanceApiV1GameInstancesInstanceIdGet(requestParameters: GetInstanceApiV1GameInstancesInstanceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SingleGameInstanceResponse> {
        const response = await this.getInstanceApiV1GameInstancesInstanceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getLevelApiV1LevelsLevelIdGet without sending the request
     */
    async getLevelApiV1LevelsLevelIdGetRequestOpts(requestParameters: GetLevelApiV1LevelsLevelIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['levelId'] == null) {
            throw new runtime.RequiredError(
                'levelId',
                'Required parameter "levelId" was null or undefined when calling getLevelApiV1LevelsLevelIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/levels/{level_id}`;
        urlPath = urlPath.replace(`{${"level_id"}}`, encodeURIComponent(String(requestParameters['levelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene los detalles de un nivel específico.  - **level_id**: ID del nivel a obtener
     * Get Level
     */
    async getLevelApiV1LevelsLevelIdGetRaw(requestParameters: GetLevelApiV1LevelsLevelIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SingleLevelResponse>> {
        const requestOptions = await this.getLevelApiV1LevelsLevelIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SingleLevelResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene los detalles de un nivel específico.  - **level_id**: ID del nivel a obtener
     * Get Level
     */
    async getLevelApiV1LevelsLevelIdGet(requestParameters: GetLevelApiV1LevelsLevelIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SingleLevelResponse> {
        const response = await this.getLevelApiV1LevelsLevelIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getLevelSegmentsApiV1SegmentsLevelIdSegmentsGet without sending the request
     */
    async getLevelSegmentsApiV1SegmentsLevelIdSegmentsGetRequestOpts(requestParameters: GetLevelSegmentsApiV1SegmentsLevelIdSegmentsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['levelId'] == null) {
            throw new runtime.RequiredError(
                'levelId',
                'Required parameter "levelId" was null or undefined when calling getLevelSegmentsApiV1SegmentsLevelIdSegmentsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/segments/{level_id}/segments`;
        urlPath = urlPath.replace(`{${"level_id"}}`, encodeURIComponent(String(requestParameters['levelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lista los segmentos de un nivel con paginación.  - **level_id**: ID del nivel - **skip**: Número de registros a saltar - **limit**: Número máximo de registros a devolver
     * Get Level Segments
     */
    async getLevelSegmentsApiV1SegmentsLevelIdSegmentsGetRaw(requestParameters: GetLevelSegmentsApiV1SegmentsLevelIdSegmentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SegmentLevelListResponse>> {
        const requestOptions = await this.getLevelSegmentsApiV1SegmentsLevelIdSegmentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SegmentLevelListResponseFromJSON(jsonValue));
    }

    /**
     * Lista los segmentos de un nivel con paginación.  - **level_id**: ID del nivel - **skip**: Número de registros a saltar - **limit**: Número máximo de registros a devolver
     * Get Level Segments
     */
    async getLevelSegmentsApiV1SegmentsLevelIdSegmentsGet(requestParameters: GetLevelSegmentsApiV1SegmentsLevelIdSegmentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SegmentLevelListResponse> {
        const response = await this.getLevelSegmentsApiV1SegmentsLevelIdSegmentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listGameInstancesApiV1GameInstancesGameIdInstancesGet without sending the request
     */
    async listGameInstancesApiV1GameInstancesGameIdInstancesGetRequestOpts(requestParameters: ListGameInstancesApiV1GameInstancesGameIdInstancesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['gameId'] == null) {
            throw new runtime.RequiredError(
                'gameId',
                'Required parameter "gameId" was null or undefined when calling listGameInstancesApiV1GameInstancesGameIdInstancesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['statusFilter'] != null) {
            queryParameters['status_filter'] = requestParameters['statusFilter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/game-instances/{game_id}/instances`;
        urlPath = urlPath.replace(`{${"game_id"}}`, encodeURIComponent(String(requestParameters['gameId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lista las instancias de un juego con paginación.  - **game_id**: ID del juego - **skip**: Número de registros a saltar - **limit**: Número máximo de registros a devolver - **status_filter**: Filtrar por estado (opcional)
     * List Game Instances
     */
    async listGameInstancesApiV1GameInstancesGameIdInstancesGetRaw(requestParameters: ListGameInstancesApiV1GameInstancesGameIdInstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameInstanceListResponse>> {
        const requestOptions = await this.listGameInstancesApiV1GameInstancesGameIdInstancesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameInstanceListResponseFromJSON(jsonValue));
    }

    /**
     * Lista las instancias de un juego con paginación.  - **game_id**: ID del juego - **skip**: Número de registros a saltar - **limit**: Número máximo de registros a devolver - **status_filter**: Filtrar por estado (opcional)
     * List Game Instances
     */
    async listGameInstancesApiV1GameInstancesGameIdInstancesGet(requestParameters: ListGameInstancesApiV1GameInstancesGameIdInstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameInstanceListResponse> {
        const response = await this.listGameInstancesApiV1GameInstancesGameIdInstancesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateGameApiV1GamesGameIdPut without sending the request
     */
    async updateGameApiV1GamesGameIdPutRequestOpts(requestParameters: UpdateGameApiV1GamesGameIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['gameId'] == null) {
            throw new runtime.RequiredError(
                'gameId',
                'Required parameter "gameId" was null or undefined when calling updateGameApiV1GamesGameIdPut().'
            );
        }

        if (requestParameters['gameUpdate'] == null) {
            throw new runtime.RequiredError(
                'gameUpdate',
                'Required parameter "gameUpdate" was null or undefined when calling updateGameApiV1GamesGameIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/games/{game_id}`;
        urlPath = urlPath.replace(`{${"game_id"}}`, encodeURIComponent(String(requestParameters['gameId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: GameUpdateToJSON(requestParameters['gameUpdate']),
        };
    }

    /**
     * Actualiza un juego existente.  - **game_id**: ID del juego a actualizar - **title**: Nuevo título (opcional) - **description**: Nueva descripción (opcional) - **creator**: Nuevo creador (opcional) - **subject**: Nueva materia (opcional) - **publication_status**: Nuevo estado (opcional)
     * Update Game
     */
    async updateGameApiV1GamesGameIdPutRaw(requestParameters: UpdateGameApiV1GamesGameIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameUpdateResponse>> {
        const requestOptions = await this.updateGameApiV1GamesGameIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameUpdateResponseFromJSON(jsonValue));
    }

    /**
     * Actualiza un juego existente.  - **game_id**: ID del juego a actualizar - **title**: Nuevo título (opcional) - **description**: Nueva descripción (opcional) - **creator**: Nuevo creador (opcional) - **subject**: Nueva materia (opcional) - **publication_status**: Nuevo estado (opcional)
     * Update Game
     */
    async updateGameApiV1GamesGameIdPut(requestParameters: UpdateGameApiV1GamesGameIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameUpdateResponse> {
        const response = await this.updateGameApiV1GamesGameIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateLevelApiV1LevelsLevelIdPut without sending the request
     */
    async updateLevelApiV1LevelsLevelIdPutRequestOpts(requestParameters: UpdateLevelApiV1LevelsLevelIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['levelId'] == null) {
            throw new runtime.RequiredError(
                'levelId',
                'Required parameter "levelId" was null or undefined when calling updateLevelApiV1LevelsLevelIdPut().'
            );
        }

        if (requestParameters['levelUpdate'] == null) {
            throw new runtime.RequiredError(
                'levelUpdate',
                'Required parameter "levelUpdate" was null or undefined when calling updateLevelApiV1LevelsLevelIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/levels/{level_id}`;
        urlPath = urlPath.replace(`{${"level_id"}}`, encodeURIComponent(String(requestParameters['levelId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LevelUpdateToJSON(requestParameters['levelUpdate']),
        };
    }

    /**
     * Actualiza un nivel existente.  - **level_id**: ID del nivel a actualizar - **level_number**: Nuevo número de nivel (opcional) - **title**: Nuevo título (opcional) - **description**: Nueva descripción (opcional) - **goal**: Nuevo objetivo (opcional)
     * Update Level
     */
    async updateLevelApiV1LevelsLevelIdPutRaw(requestParameters: UpdateLevelApiV1LevelsLevelIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LevelUpdateResponse>> {
        const requestOptions = await this.updateLevelApiV1LevelsLevelIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LevelUpdateResponseFromJSON(jsonValue));
    }

    /**
     * Actualiza un nivel existente.  - **level_id**: ID del nivel a actualizar - **level_number**: Nuevo número de nivel (opcional) - **title**: Nuevo título (opcional) - **description**: Nueva descripción (opcional) - **goal**: Nuevo objetivo (opcional)
     * Update Level
     */
    async updateLevelApiV1LevelsLevelIdPut(requestParameters: UpdateLevelApiV1LevelsLevelIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LevelUpdateResponse> {
        const response = await this.updateLevelApiV1LevelsLevelIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSegmentApiV1SegmentsSegmentIdPut without sending the request
     */
    async updateSegmentApiV1SegmentsSegmentIdPutRequestOpts(requestParameters: UpdateSegmentApiV1SegmentsSegmentIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['segmentId'] == null) {
            throw new runtime.RequiredError(
                'segmentId',
                'Required parameter "segmentId" was null or undefined when calling updateSegmentApiV1SegmentsSegmentIdPut().'
            );
        }

        if (requestParameters['segmentLevelUpdate'] == null) {
            throw new runtime.RequiredError(
                'segmentLevelUpdate',
                'Required parameter "segmentLevelUpdate" was null or undefined when calling updateSegmentApiV1SegmentsSegmentIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/segments/{segment_id}`;
        urlPath = urlPath.replace(`{${"segment_id"}}`, encodeURIComponent(String(requestParameters['segmentId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SegmentLevelUpdateToJSON(requestParameters['segmentLevelUpdate']),
        };
    }

    /**
     * Actualiza un segmento existente.  - **segment_id**: ID del segmento a actualizar - **configuration**: Nueva configuración JSON (opcional)
     * Update Segment
     */
    async updateSegmentApiV1SegmentsSegmentIdPutRaw(requestParameters: UpdateSegmentApiV1SegmentsSegmentIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SegmentLevelUpdateResponse>> {
        const requestOptions = await this.updateSegmentApiV1SegmentsSegmentIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SegmentLevelUpdateResponseFromJSON(jsonValue));
    }

    /**
     * Actualiza un segmento existente.  - **segment_id**: ID del segmento a actualizar - **configuration**: Nueva configuración JSON (opcional)
     * Update Segment
     */
    async updateSegmentApiV1SegmentsSegmentIdPut(requestParameters: UpdateSegmentApiV1SegmentsSegmentIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SegmentLevelUpdateResponse> {
        const response = await this.updateSegmentApiV1SegmentsSegmentIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
