/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  LMSCredentialCreate,
  LMSCredentialResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LMSCredentialCreateFromJSON,
    LMSCredentialCreateToJSON,
    LMSCredentialResponseFromJSON,
    LMSCredentialResponseToJSON,
} from '../models/index';

export interface DeleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequest {
    userId: number;
}

export interface GetUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequest {
    userId: number;
}

export interface RegisterLmsCredentialsApiV1UsersLmsCredentialsPostRequest {
    lMSCredentialCreate: LMSCredentialCreate;
}

/**
 * 
 */
export class LMSCredentialsApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDelete without sending the request
     */
    async deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequestOpts(requestParameters: DeleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/users/lms/credentials/user/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Eliminar las credenciales LMS de un usuario.  Realiza un soft delete de las credenciales.
     * Delete User Lms Credentials
     */
    async deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRaw(requestParameters: DeleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Eliminar las credenciales LMS de un usuario.  Realiza un soft delete de las credenciales.
     * Delete User Lms Credentials
     */
    async deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDelete(requestParameters: DeleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGet without sending the request
     */
    async getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequestOpts(requestParameters: GetUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/users/lms/credentials/user/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener las credenciales LMS de un usuario.  Retorna las credenciales con la contraseña oculta.
     * Get User Lms Credentials
     */
    async getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRaw(requestParameters: GetUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LMSCredentialResponse>> {
        const requestOptions = await this.getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LMSCredentialResponseFromJSON(jsonValue));
    }

    /**
     * Obtener las credenciales LMS de un usuario.  Retorna las credenciales con la contraseña oculta.
     * Get User Lms Credentials
     */
    async getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGet(requestParameters: GetUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LMSCredentialResponse> {
        const response = await this.getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerLmsCredentialsApiV1UsersLmsCredentialsPost without sending the request
     */
    async registerLmsCredentialsApiV1UsersLmsCredentialsPostRequestOpts(requestParameters: RegisterLmsCredentialsApiV1UsersLmsCredentialsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['lMSCredentialCreate'] == null) {
            throw new runtime.RequiredError(
                'lMSCredentialCreate',
                'Required parameter "lMSCredentialCreate" was null or undefined when calling registerLmsCredentialsApiV1UsersLmsCredentialsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/users/lms/credentials`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LMSCredentialCreateToJSON(requestParameters['lMSCredentialCreate']),
        };
    }

    /**
     * Registrar credenciales LMS para un usuario.  - **user_id**: ID del usuario que registra las credenciales - **lms_url**: URL del LMS (ej: https://moodle.university.edu) - **lms_email**: Email de la cuenta en el LMS - **lms_password**: Contraseña de la cuenta LMS - **lms_provider**: Proveedor LMS (moodle, canvas, etc.)
     * Register Lms Credentials
     */
    async registerLmsCredentialsApiV1UsersLmsCredentialsPostRaw(requestParameters: RegisterLmsCredentialsApiV1UsersLmsCredentialsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LMSCredentialResponse>> {
        const requestOptions = await this.registerLmsCredentialsApiV1UsersLmsCredentialsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LMSCredentialResponseFromJSON(jsonValue));
    }

    /**
     * Registrar credenciales LMS para un usuario.  - **user_id**: ID del usuario que registra las credenciales - **lms_url**: URL del LMS (ej: https://moodle.university.edu) - **lms_email**: Email de la cuenta en el LMS - **lms_password**: Contraseña de la cuenta LMS - **lms_provider**: Proveedor LMS (moodle, canvas, etc.)
     * Register Lms Credentials
     */
    async registerLmsCredentialsApiV1UsersLmsCredentialsPost(requestParameters: RegisterLmsCredentialsApiV1UsersLmsCredentialsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LMSCredentialResponse> {
        const response = await this.registerLmsCredentialsApiV1UsersLmsCredentialsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
