/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FeedbackCreate,
  FeedbackSchema,
  HTTPValidationError,
  MetricTypeCreate,
  MetricTypeSchema,
  MetricTypeUpdate,
  XAPIStatementBatchCreate,
  XAPIStatementListResponse,
  XAPIStatementResponse,
} from '../models/index';
import {
    FeedbackCreateFromJSON,
    FeedbackCreateToJSON,
    FeedbackSchemaFromJSON,
    FeedbackSchemaToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MetricTypeCreateFromJSON,
    MetricTypeCreateToJSON,
    MetricTypeSchemaFromJSON,
    MetricTypeSchemaToJSON,
    MetricTypeUpdateFromJSON,
    MetricTypeUpdateToJSON,
    XAPIStatementBatchCreateFromJSON,
    XAPIStatementBatchCreateToJSON,
    XAPIStatementListResponseFromJSON,
    XAPIStatementListResponseToJSON,
    XAPIStatementResponseFromJSON,
    XAPIStatementResponseToJSON,
} from '../models/index';

export interface CreateMetricTypeApiV1StatisticMetricTypesPostRequest {
    metricTypeCreate: MetricTypeCreate;
}

export interface DeleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDeleteRequest {
    metricTypeId: number;
}

export interface GetMetricTypeApiV1StatisticMetricTypesMetricTypeIdGetRequest {
    metricTypeId: number;
}

export interface GetStatementApiV1StatisticXapiStatementsStatementIdGetRequest {
    statementId: string;
}

export interface GetStatementsApiV1StatisticXapiStatementsGetRequest {
    skip?: number;
    limit?: number;
    studentId?: number | null;
    verbId?: string | null;
    gameId?: number | null;
    levelId?: number | null;
}

export interface GetStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGetRequest {
    studentId: number;
    skip?: number;
    limit?: number;
}

export interface ListMetricTypesApiV1StatisticMetricTypesGetRequest {
    skip?: number;
    limit?: number;
}

export interface SendStatementsApiV1StatisticXapiStatementsPostRequest {
    xAPIStatementBatchCreate: XAPIStatementBatchCreate;
}

export interface SubmitFeedbackApiV1StatisticFeedbackPostRequest {
    feedbackCreate: FeedbackCreate;
}

export interface UpdateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatchRequest {
    metricTypeId: number;
    metricTypeUpdate: MetricTypeUpdate;
}

/**
 * 
 */
export class StatisticsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createMetricTypeApiV1StatisticMetricTypesPost without sending the request
     */
    async createMetricTypeApiV1StatisticMetricTypesPostRequestOpts(requestParameters: CreateMetricTypeApiV1StatisticMetricTypesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['metricTypeCreate'] == null) {
            throw new runtime.RequiredError(
                'metricTypeCreate',
                'Required parameter "metricTypeCreate" was null or undefined when calling createMetricTypeApiV1StatisticMetricTypesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/metric-types`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MetricTypeCreateToJSON(requestParameters['metricTypeCreate']),
        };
    }

    /**
     * Crea un nuevo tipo de métrica.
     * Create Metric Type
     */
    async createMetricTypeApiV1StatisticMetricTypesPostRaw(requestParameters: CreateMetricTypeApiV1StatisticMetricTypesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetricTypeSchema>> {
        const requestOptions = await this.createMetricTypeApiV1StatisticMetricTypesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetricTypeSchemaFromJSON(jsonValue));
    }

    /**
     * Crea un nuevo tipo de métrica.
     * Create Metric Type
     */
    async createMetricTypeApiV1StatisticMetricTypesPost(requestParameters: CreateMetricTypeApiV1StatisticMetricTypesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetricTypeSchema> {
        const response = await this.createMetricTypeApiV1StatisticMetricTypesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDelete without sending the request
     */
    async deleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDeleteRequestOpts(requestParameters: DeleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['metricTypeId'] == null) {
            throw new runtime.RequiredError(
                'metricTypeId',
                'Required parameter "metricTypeId" was null or undefined when calling deleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/metric-types/{metric_type_id}`;
        urlPath = urlPath.replace(`{${"metric_type_id"}}`, encodeURIComponent(String(requestParameters['metricTypeId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Elimina un tipo de métrica (soft delete).
     * Delete Metric Type
     */
    async deleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDeleteRaw(requestParameters: DeleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Elimina un tipo de métrica (soft delete).
     * Delete Metric Type
     */
    async deleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDelete(requestParameters: DeleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMetricTypeApiV1StatisticMetricTypesMetricTypeIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getMetricTypeApiV1StatisticMetricTypesMetricTypeIdGet without sending the request
     */
    async getMetricTypeApiV1StatisticMetricTypesMetricTypeIdGetRequestOpts(requestParameters: GetMetricTypeApiV1StatisticMetricTypesMetricTypeIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['metricTypeId'] == null) {
            throw new runtime.RequiredError(
                'metricTypeId',
                'Required parameter "metricTypeId" was null or undefined when calling getMetricTypeApiV1StatisticMetricTypesMetricTypeIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/metric-types/{metric_type_id}`;
        urlPath = urlPath.replace(`{${"metric_type_id"}}`, encodeURIComponent(String(requestParameters['metricTypeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene un tipo de métrica por su ID.
     * Get Metric Type
     */
    async getMetricTypeApiV1StatisticMetricTypesMetricTypeIdGetRaw(requestParameters: GetMetricTypeApiV1StatisticMetricTypesMetricTypeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetricTypeSchema>> {
        const requestOptions = await this.getMetricTypeApiV1StatisticMetricTypesMetricTypeIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetricTypeSchemaFromJSON(jsonValue));
    }

    /**
     * Obtiene un tipo de métrica por su ID.
     * Get Metric Type
     */
    async getMetricTypeApiV1StatisticMetricTypesMetricTypeIdGet(requestParameters: GetMetricTypeApiV1StatisticMetricTypesMetricTypeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetricTypeSchema> {
        const response = await this.getMetricTypeApiV1StatisticMetricTypesMetricTypeIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStatementApiV1StatisticXapiStatementsStatementIdGet without sending the request
     */
    async getStatementApiV1StatisticXapiStatementsStatementIdGetRequestOpts(requestParameters: GetStatementApiV1StatisticXapiStatementsStatementIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['statementId'] == null) {
            throw new runtime.RequiredError(
                'statementId',
                'Required parameter "statementId" was null or undefined when calling getStatementApiV1StatisticXapiStatementsStatementIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/xapi/statements/{statement_id}`;
        urlPath = urlPath.replace(`{${"statement_id"}}`, encodeURIComponent(String(requestParameters['statementId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a specific xAPI statement by ID.
     * Get Statement
     */
    async getStatementApiV1StatisticXapiStatementsStatementIdGetRaw(requestParameters: GetStatementApiV1StatisticXapiStatementsStatementIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<XAPIStatementResponse>> {
        const requestOptions = await this.getStatementApiV1StatisticXapiStatementsStatementIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => XAPIStatementResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific xAPI statement by ID.
     * Get Statement
     */
    async getStatementApiV1StatisticXapiStatementsStatementIdGet(requestParameters: GetStatementApiV1StatisticXapiStatementsStatementIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<XAPIStatementResponse> {
        const response = await this.getStatementApiV1StatisticXapiStatementsStatementIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStatementsApiV1StatisticXapiStatementsGet without sending the request
     */
    async getStatementsApiV1StatisticXapiStatementsGetRequestOpts(requestParameters: GetStatementsApiV1StatisticXapiStatementsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['studentId'] != null) {
            queryParameters['student_id'] = requestParameters['studentId'];
        }

        if (requestParameters['verbId'] != null) {
            queryParameters['verb_id'] = requestParameters['verbId'];
        }

        if (requestParameters['gameId'] != null) {
            queryParameters['game_id'] = requestParameters['gameId'];
        }

        if (requestParameters['levelId'] != null) {
            queryParameters['level_id'] = requestParameters['levelId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/xapi/statements`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get xAPI statements with optional filters.  Returns statements with pagination. Use filters to narrow results.
     * Get Statements
     */
    async getStatementsApiV1StatisticXapiStatementsGetRaw(requestParameters: GetStatementsApiV1StatisticXapiStatementsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<XAPIStatementListResponse>> {
        const requestOptions = await this.getStatementsApiV1StatisticXapiStatementsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => XAPIStatementListResponseFromJSON(jsonValue));
    }

    /**
     * Get xAPI statements with optional filters.  Returns statements with pagination. Use filters to narrow results.
     * Get Statements
     */
    async getStatementsApiV1StatisticXapiStatementsGet(requestParameters: GetStatementsApiV1StatisticXapiStatementsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<XAPIStatementListResponse> {
        const response = await this.getStatementsApiV1StatisticXapiStatementsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGet without sending the request
     */
    async getStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGetRequestOpts(requestParameters: GetStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['studentId'] == null) {
            throw new runtime.RequiredError(
                'studentId',
                'Required parameter "studentId" was null or undefined when calling getStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/feedback/{student_id}`;
        urlPath = urlPath.replace(`{${"student_id"}}`, encodeURIComponent(String(requestParameters['studentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener feedback histórico del estudiante.
     * Get Student Feedback History
     */
    async getStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGetRaw(requestParameters: GetStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FeedbackSchema>>> {
        const requestOptions = await this.getStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FeedbackSchemaFromJSON));
    }

    /**
     * Obtener feedback histórico del estudiante.
     * Get Student Feedback History
     */
    async getStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGet(requestParameters: GetStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FeedbackSchema>> {
        const response = await this.getStudentFeedbackHistoryApiV1StatisticFeedbackStudentIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMetricTypesApiV1StatisticMetricTypesGet without sending the request
     */
    async listMetricTypesApiV1StatisticMetricTypesGetRequestOpts(requestParameters: ListMetricTypesApiV1StatisticMetricTypesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/metric-types`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lista todos los tipos de métricas disponibles.
     * List Metric Types
     */
    async listMetricTypesApiV1StatisticMetricTypesGetRaw(requestParameters: ListMetricTypesApiV1StatisticMetricTypesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MetricTypeSchema>>> {
        const requestOptions = await this.listMetricTypesApiV1StatisticMetricTypesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetricTypeSchemaFromJSON));
    }

    /**
     * Lista todos los tipos de métricas disponibles.
     * List Metric Types
     */
    async listMetricTypesApiV1StatisticMetricTypesGet(requestParameters: ListMetricTypesApiV1StatisticMetricTypesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MetricTypeSchema>> {
        const response = await this.listMetricTypesApiV1StatisticMetricTypesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendStatementsApiV1StatisticXapiStatementsPost without sending the request
     */
    async sendStatementsApiV1StatisticXapiStatementsPostRequestOpts(requestParameters: SendStatementsApiV1StatisticXapiStatementsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xAPIStatementBatchCreate'] == null) {
            throw new runtime.RequiredError(
                'xAPIStatementBatchCreate',
                'Required parameter "xAPIStatementBatchCreate" was null or undefined when calling sendStatementsApiV1StatisticXapiStatementsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/xapi/statements`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: XAPIStatementBatchCreateToJSON(requestParameters['xAPIStatementBatchCreate']),
        };
    }

    /**
     * Receive and store xAPI statements.  Accepts a batch of xAPI statements (1-1000 per request). Supports full xAPI 1.0 specification with game-specific context.  The game client should send statements with: - actor.account.name = student_id - verb = standard xAPI verb - object.id = activity ID (e.g., hello-world://segment/level_1_seg_3) - result = quantitative data (score, success, completion) - context = qualitative data (platform, language, extensions) - context.extensions = game-specific data (game_id, level_id, segment_id)
     * Send Statements
     */
    async sendStatementsApiV1StatisticXapiStatementsPostRaw(requestParameters: SendStatementsApiV1StatisticXapiStatementsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<XAPIStatementResponse>>> {
        const requestOptions = await this.sendStatementsApiV1StatisticXapiStatementsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(XAPIStatementResponseFromJSON));
    }

    /**
     * Receive and store xAPI statements.  Accepts a batch of xAPI statements (1-1000 per request). Supports full xAPI 1.0 specification with game-specific context.  The game client should send statements with: - actor.account.name = student_id - verb = standard xAPI verb - object.id = activity ID (e.g., hello-world://segment/level_1_seg_3) - result = quantitative data (score, success, completion) - context = qualitative data (platform, language, extensions) - context.extensions = game-specific data (game_id, level_id, segment_id)
     * Send Statements
     */
    async sendStatementsApiV1StatisticXapiStatementsPost(requestParameters: SendStatementsApiV1StatisticXapiStatementsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<XAPIStatementResponse>> {
        const response = await this.sendStatementsApiV1StatisticXapiStatementsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitFeedbackApiV1StatisticFeedbackPost without sending the request
     */
    async submitFeedbackApiV1StatisticFeedbackPostRequestOpts(requestParameters: SubmitFeedbackApiV1StatisticFeedbackPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['feedbackCreate'] == null) {
            throw new runtime.RequiredError(
                'feedbackCreate',
                'Required parameter "feedbackCreate" was null or undefined when calling submitFeedbackApiV1StatisticFeedbackPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/feedback`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FeedbackCreateToJSON(requestParameters['feedbackCreate']),
        };
    }

    /**
     * Enviar retroalimentación de un estudiante.
     * Submit Feedback
     */
    async submitFeedbackApiV1StatisticFeedbackPostRaw(requestParameters: SubmitFeedbackApiV1StatisticFeedbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeedbackSchema>> {
        const requestOptions = await this.submitFeedbackApiV1StatisticFeedbackPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedbackSchemaFromJSON(jsonValue));
    }

    /**
     * Enviar retroalimentación de un estudiante.
     * Submit Feedback
     */
    async submitFeedbackApiV1StatisticFeedbackPost(requestParameters: SubmitFeedbackApiV1StatisticFeedbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeedbackSchema> {
        const response = await this.submitFeedbackApiV1StatisticFeedbackPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatch without sending the request
     */
    async updateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatchRequestOpts(requestParameters: UpdateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['metricTypeId'] == null) {
            throw new runtime.RequiredError(
                'metricTypeId',
                'Required parameter "metricTypeId" was null or undefined when calling updateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatch().'
            );
        }

        if (requestParameters['metricTypeUpdate'] == null) {
            throw new runtime.RequiredError(
                'metricTypeUpdate',
                'Required parameter "metricTypeUpdate" was null or undefined when calling updateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/metric-types/{metric_type_id}`;
        urlPath = urlPath.replace(`{${"metric_type_id"}}`, encodeURIComponent(String(requestParameters['metricTypeId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MetricTypeUpdateToJSON(requestParameters['metricTypeUpdate']),
        };
    }

    /**
     * Actualiza un tipo de métrica existente.
     * Update Metric Type
     */
    async updateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatchRaw(requestParameters: UpdateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetricTypeSchema>> {
        const requestOptions = await this.updateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetricTypeSchemaFromJSON(jsonValue));
    }

    /**
     * Actualiza un tipo de métrica existente.
     * Update Metric Type
     */
    async updateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatch(requestParameters: UpdateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetricTypeSchema> {
        const response = await this.updateMetricTypeApiV1StatisticMetricTypesMetricTypeIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
