/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  LMSCredentialCreate,
  LMSCredentialResponse,
  SingleUserResponse,
  StudentCreate,
  StudentListResponse,
  StudentProgressResponse,
  StudentReportsResponse,
  StudentResponse,
  StudentUpdate,
  SyncResultResponse,
  TeacherProfileResponseSchema,
  TeacherProfileUpdate,
  TeacherSettingsResponseSchema,
  TeacherSettingsUpdate,
  TeacherUpdateResponseSchema,
  UserCreate,
  UserListResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LMSCredentialCreateFromJSON,
    LMSCredentialCreateToJSON,
    LMSCredentialResponseFromJSON,
    LMSCredentialResponseToJSON,
    SingleUserResponseFromJSON,
    SingleUserResponseToJSON,
    StudentCreateFromJSON,
    StudentCreateToJSON,
    StudentListResponseFromJSON,
    StudentListResponseToJSON,
    StudentProgressResponseFromJSON,
    StudentProgressResponseToJSON,
    StudentReportsResponseFromJSON,
    StudentReportsResponseToJSON,
    StudentResponseFromJSON,
    StudentResponseToJSON,
    StudentUpdateFromJSON,
    StudentUpdateToJSON,
    SyncResultResponseFromJSON,
    SyncResultResponseToJSON,
    TeacherProfileResponseSchemaFromJSON,
    TeacherProfileResponseSchemaToJSON,
    TeacherProfileUpdateFromJSON,
    TeacherProfileUpdateToJSON,
    TeacherSettingsResponseSchemaFromJSON,
    TeacherSettingsResponseSchemaToJSON,
    TeacherSettingsUpdateFromJSON,
    TeacherSettingsUpdateToJSON,
    TeacherUpdateResponseSchemaFromJSON,
    TeacherUpdateResponseSchemaToJSON,
    UserCreateFromJSON,
    UserCreateToJSON,
    UserListResponseFromJSON,
    UserListResponseToJSON,
} from '../models/index';

export interface CreateStudentApiV1UsersStudentsPostRequest {
    studentCreate: StudentCreate;
}

export interface CreateUserApiV1UsersPostRequest {
    userCreate: UserCreate;
}

export interface DeleteStudentApiV1UsersStudentsIdDeleteRequest {
    id: number;
}

export interface DeleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequest {
    userId: number;
}

export interface GetAllUsersApiV1UsersGetRequest {
    skip?: number;
    limit?: number;
    includeDeleted?: boolean;
}

export interface GetStudentApiV1UsersStudentsIdGetRequest {
    id: number;
}

export interface GetStudentProgressApiV1UsersStudentsIdProgressGetRequest {
    id: number;
}

export interface GetStudentReportsApiV1UsersStudentsIdReportsGetRequest {
    id: number;
}

export interface GetUserApiV1UsersUserIdGetRequest {
    userId: number;
}

export interface GetUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequest {
    userId: number;
}

export interface ListStudentsApiV1UsersStudentsGetRequest {
    skip?: number;
    limit?: number;
    search?: string;
}

export interface RegisterLmsCredentialsApiV1UsersLmsCredentialsPostRequest {
    lMSCredentialCreate: LMSCredentialCreate;
}

export interface SyncLmsDataApiV1UsersLmsSyncUserIdPostRequest {
    userId: number;
}

export interface UpdateStudentApiV1UsersStudentsIdPutRequest {
    id: number;
    studentUpdate: StudentUpdate;
}

export interface UpdateTeacherProfileApiV1UsersProfessorsMePutRequest {
    teacherProfileUpdate: TeacherProfileUpdate;
}

export interface UpdateTeacherSettingsApiV1UsersProfessorsSettingsPutRequest {
    teacherSettingsUpdate: TeacherSettingsUpdate;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Creates request options for createStudentApiV1UsersStudentsPost without sending the request
     */
    async createStudentApiV1UsersStudentsPostRequestOpts(requestParameters: CreateStudentApiV1UsersStudentsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['studentCreate'] == null) {
            throw new runtime.RequiredError(
                'studentCreate',
                'Required parameter "studentCreate" was null or undefined when calling createStudentApiV1UsersStudentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/students`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StudentCreateToJSON(requestParameters['studentCreate']),
        };
    }

    /**
     * Registrar un nuevo estudiante.  Requiere autenticación y rol de professor o admin.
     * Create Student
     */
    async createStudentApiV1UsersStudentsPostRaw(requestParameters: CreateStudentApiV1UsersStudentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentResponse>> {
        const requestOptions = await this.createStudentApiV1UsersStudentsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentResponseFromJSON(jsonValue));
    }

    /**
     * Registrar un nuevo estudiante.  Requiere autenticación y rol de professor o admin.
     * Create Student
     */
    async createStudentApiV1UsersStudentsPost(requestParameters: CreateStudentApiV1UsersStudentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentResponse> {
        const response = await this.createStudentApiV1UsersStudentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createUserApiV1UsersPost without sending the request
     */
    async createUserApiV1UsersPostRequestOpts(requestParameters: CreateUserApiV1UsersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userCreate'] == null) {
            throw new runtime.RequiredError(
                'userCreate',
                'Required parameter "userCreate" was null or undefined when calling createUserApiV1UsersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserCreateToJSON(requestParameters['userCreate']),
        };
    }

    /**
     * Crea un nuevo usuario en la base de datos con la información proporcionada. - **email**: El correo electrónico del usuario (debe ser único). - **username**: El nombre de usuario (opcional, debe ser único si se proporciona). - **name**: El nombre del usuario (requerido). - **password**: La contraseña del usuario.
     * Crear un nuevo usuario
     */
    async createUserApiV1UsersPostRaw(requestParameters: CreateUserApiV1UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SingleUserResponse>> {
        const requestOptions = await this.createUserApiV1UsersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SingleUserResponseFromJSON(jsonValue));
    }

    /**
     * Crea un nuevo usuario en la base de datos con la información proporcionada. - **email**: El correo electrónico del usuario (debe ser único). - **username**: El nombre de usuario (opcional, debe ser único si se proporciona). - **name**: El nombre del usuario (requerido). - **password**: La contraseña del usuario.
     * Crear un nuevo usuario
     */
    async createUserApiV1UsersPost(requestParameters: CreateUserApiV1UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SingleUserResponse> {
        const response = await this.createUserApiV1UsersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteStudentApiV1UsersStudentsIdDelete without sending the request
     */
    async deleteStudentApiV1UsersStudentsIdDeleteRequestOpts(requestParameters: DeleteStudentApiV1UsersStudentsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteStudentApiV1UsersStudentsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/students/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Eliminar estudiante (soft delete).  Requiere autenticación y rol de professor o admin.
     * Delete Student
     */
    async deleteStudentApiV1UsersStudentsIdDeleteRaw(requestParameters: DeleteStudentApiV1UsersStudentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.deleteStudentApiV1UsersStudentsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Eliminar estudiante (soft delete).  Requiere autenticación y rol de professor o admin.
     * Delete Student
     */
    async deleteStudentApiV1UsersStudentsIdDelete(requestParameters: DeleteStudentApiV1UsersStudentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteStudentApiV1UsersStudentsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDelete without sending the request
     */
    async deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequestOpts(requestParameters: DeleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/lms/credentials/user/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Eliminar las credenciales LMS de un usuario.  Realiza un soft delete de las credenciales.
     * Delete User Lms Credentials
     */
    async deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRaw(requestParameters: DeleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Eliminar las credenciales LMS de un usuario.  Realiza un soft delete de las credenciales.
     * Delete User Lms Credentials
     */
    async deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDelete(requestParameters: DeleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllUsersApiV1UsersGet without sending the request
     */
    async getAllUsersApiV1UsersGetRequestOpts(requestParameters: GetAllUsersApiV1UsersGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['includeDeleted'] != null) {
            queryParameters['include_deleted'] = requestParameters['includeDeleted'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene una lista paginada de todos los usuarios registrados en el sistema.  - **include_deleted**: Si es True, incluye usuarios eliminados (soft deleted).   Por defecto es False para solo mostrar usuarios activos.
     * Obtener todos los usuarios
     */
    async getAllUsersApiV1UsersGetRaw(requestParameters: GetAllUsersApiV1UsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserListResponse>> {
        const requestOptions = await this.getAllUsersApiV1UsersGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserListResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene una lista paginada de todos los usuarios registrados en el sistema.  - **include_deleted**: Si es True, incluye usuarios eliminados (soft deleted).   Por defecto es False para solo mostrar usuarios activos.
     * Obtener todos los usuarios
     */
    async getAllUsersApiV1UsersGet(requestParameters: GetAllUsersApiV1UsersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserListResponse> {
        const response = await this.getAllUsersApiV1UsersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStudentApiV1UsersStudentsIdGet without sending the request
     */
    async getStudentApiV1UsersStudentsIdGetRequestOpts(requestParameters: GetStudentApiV1UsersStudentsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getStudentApiV1UsersStudentsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/students/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener detalle de un estudiante.  Requiere autenticación. Professor/Admin pueden ver cualquier estudiante. El propio estudiante puede ver su propio perfil.
     * Get Student
     */
    async getStudentApiV1UsersStudentsIdGetRaw(requestParameters: GetStudentApiV1UsersStudentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentResponse>> {
        const requestOptions = await this.getStudentApiV1UsersStudentsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentResponseFromJSON(jsonValue));
    }

    /**
     * Obtener detalle de un estudiante.  Requiere autenticación. Professor/Admin pueden ver cualquier estudiante. El propio estudiante puede ver su propio perfil.
     * Get Student
     */
    async getStudentApiV1UsersStudentsIdGet(requestParameters: GetStudentApiV1UsersStudentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentResponse> {
        const response = await this.getStudentApiV1UsersStudentsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStudentProgressApiV1UsersStudentsIdProgressGet without sending the request
     */
    async getStudentProgressApiV1UsersStudentsIdProgressGetRequestOpts(requestParameters: GetStudentProgressApiV1UsersStudentsIdProgressGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getStudentProgressApiV1UsersStudentsIdProgressGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/students/{id}/progress`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener progreso del estudiante.  Requiere autenticación. Professor/Admin pueden ver cualquier estudiante. El propio estudiante puede ver su propio progreso.
     * Get Student Progress
     */
    async getStudentProgressApiV1UsersStudentsIdProgressGetRaw(requestParameters: GetStudentProgressApiV1UsersStudentsIdProgressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentProgressResponse>> {
        const requestOptions = await this.getStudentProgressApiV1UsersStudentsIdProgressGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentProgressResponseFromJSON(jsonValue));
    }

    /**
     * Obtener progreso del estudiante.  Requiere autenticación. Professor/Admin pueden ver cualquier estudiante. El propio estudiante puede ver su propio progreso.
     * Get Student Progress
     */
    async getStudentProgressApiV1UsersStudentsIdProgressGet(requestParameters: GetStudentProgressApiV1UsersStudentsIdProgressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentProgressResponse> {
        const response = await this.getStudentProgressApiV1UsersStudentsIdProgressGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStudentReportsApiV1UsersStudentsIdReportsGet without sending the request
     */
    async getStudentReportsApiV1UsersStudentsIdReportsGetRequestOpts(requestParameters: GetStudentReportsApiV1UsersStudentsIdReportsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getStudentReportsApiV1UsersStudentsIdReportsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/students/{id}/reports`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener reportes individuales (desempeño, actividad, etc.)
     * Get Student Reports
     */
    async getStudentReportsApiV1UsersStudentsIdReportsGetRaw(requestParameters: GetStudentReportsApiV1UsersStudentsIdReportsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentReportsResponse>> {
        const requestOptions = await this.getStudentReportsApiV1UsersStudentsIdReportsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentReportsResponseFromJSON(jsonValue));
    }

    /**
     * Obtener reportes individuales (desempeño, actividad, etc.)
     * Get Student Reports
     */
    async getStudentReportsApiV1UsersStudentsIdReportsGet(requestParameters: GetStudentReportsApiV1UsersStudentsIdReportsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentReportsResponse> {
        const response = await this.getStudentReportsApiV1UsersStudentsIdReportsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTeacherProfileApiV1UsersProfessorsMeGet without sending the request
     */
    async getTeacherProfileApiV1UsersProfessorsMeGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/professors/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener perfil del profesor autenticado.  Requiere autenticación mediante token JWT.
     * Get Teacher Profile
     */
    async getTeacherProfileApiV1UsersProfessorsMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeacherProfileResponseSchema>> {
        const requestOptions = await this.getTeacherProfileApiV1UsersProfessorsMeGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeacherProfileResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Obtener perfil del profesor autenticado.  Requiere autenticación mediante token JWT.
     * Get Teacher Profile
     */
    async getTeacherProfileApiV1UsersProfessorsMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeacherProfileResponseSchema> {
        const response = await this.getTeacherProfileApiV1UsersProfessorsMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTeacherSettingsApiV1UsersProfessorsSettingsGet without sending the request
     */
    async getTeacherSettingsApiV1UsersProfessorsSettingsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/professors/settings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener configuraciones del dashboard del profesor.  Requiere autenticación mediante token JWT.
     * Get Teacher Settings
     */
    async getTeacherSettingsApiV1UsersProfessorsSettingsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeacherSettingsResponseSchema>> {
        const requestOptions = await this.getTeacherSettingsApiV1UsersProfessorsSettingsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeacherSettingsResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Obtener configuraciones del dashboard del profesor.  Requiere autenticación mediante token JWT.
     * Get Teacher Settings
     */
    async getTeacherSettingsApiV1UsersProfessorsSettingsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeacherSettingsResponseSchema> {
        const response = await this.getTeacherSettingsApiV1UsersProfessorsSettingsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserApiV1UsersUserIdGet without sending the request
     */
    async getUserApiV1UsersUserIdGetRequestOpts(requestParameters: GetUserApiV1UsersUserIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserApiV1UsersUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Busca y devuelve un usuario por su ID único.
     * Obtener un usuario por ID
     */
    async getUserApiV1UsersUserIdGetRaw(requestParameters: GetUserApiV1UsersUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SingleUserResponse>> {
        const requestOptions = await this.getUserApiV1UsersUserIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SingleUserResponseFromJSON(jsonValue));
    }

    /**
     * Busca y devuelve un usuario por su ID único.
     * Obtener un usuario por ID
     */
    async getUserApiV1UsersUserIdGet(requestParameters: GetUserApiV1UsersUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SingleUserResponse> {
        const response = await this.getUserApiV1UsersUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGet without sending the request
     */
    async getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequestOpts(requestParameters: GetUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/lms/credentials/user/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener las credenciales LMS de un usuario.  Retorna las credenciales con la contraseña oculta.
     * Get User Lms Credentials
     */
    async getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRaw(requestParameters: GetUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LMSCredentialResponse>> {
        const requestOptions = await this.getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LMSCredentialResponseFromJSON(jsonValue));
    }

    /**
     * Obtener las credenciales LMS de un usuario.  Retorna las credenciales con la contraseña oculta.
     * Get User Lms Credentials
     */
    async getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGet(requestParameters: GetUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LMSCredentialResponse> {
        const response = await this.getUserLmsCredentialsApiV1UsersLmsCredentialsUserUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listStudentsApiV1UsersStudentsGet without sending the request
     */
    async listStudentsApiV1UsersStudentsGetRequestOpts(requestParameters: ListStudentsApiV1UsersStudentsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/students`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Listar estudiantes (con filtros y paginación).  Requiere autenticación y rol de professor o admin.
     * List Students
     */
    async listStudentsApiV1UsersStudentsGetRaw(requestParameters: ListStudentsApiV1UsersStudentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentListResponse>> {
        const requestOptions = await this.listStudentsApiV1UsersStudentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentListResponseFromJSON(jsonValue));
    }

    /**
     * Listar estudiantes (con filtros y paginación).  Requiere autenticación y rol de professor o admin.
     * List Students
     */
    async listStudentsApiV1UsersStudentsGet(requestParameters: ListStudentsApiV1UsersStudentsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentListResponse> {
        const response = await this.listStudentsApiV1UsersStudentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerLmsCredentialsApiV1UsersLmsCredentialsPost without sending the request
     */
    async registerLmsCredentialsApiV1UsersLmsCredentialsPostRequestOpts(requestParameters: RegisterLmsCredentialsApiV1UsersLmsCredentialsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['lMSCredentialCreate'] == null) {
            throw new runtime.RequiredError(
                'lMSCredentialCreate',
                'Required parameter "lMSCredentialCreate" was null or undefined when calling registerLmsCredentialsApiV1UsersLmsCredentialsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/lms/credentials`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LMSCredentialCreateToJSON(requestParameters['lMSCredentialCreate']),
        };
    }

    /**
     * Registrar credenciales LMS para un usuario.  - **user_id**: ID del usuario que registra las credenciales - **lms_url**: URL del LMS (ej: https://moodle.university.edu) - **lms_email**: Email de la cuenta en el LMS - **lms_password**: Contraseña de la cuenta LMS - **lms_provider**: Proveedor LMS (moodle, canvas, etc.)
     * Register Lms Credentials
     */
    async registerLmsCredentialsApiV1UsersLmsCredentialsPostRaw(requestParameters: RegisterLmsCredentialsApiV1UsersLmsCredentialsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LMSCredentialResponse>> {
        const requestOptions = await this.registerLmsCredentialsApiV1UsersLmsCredentialsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LMSCredentialResponseFromJSON(jsonValue));
    }

    /**
     * Registrar credenciales LMS para un usuario.  - **user_id**: ID del usuario que registra las credenciales - **lms_url**: URL del LMS (ej: https://moodle.university.edu) - **lms_email**: Email de la cuenta en el LMS - **lms_password**: Contraseña de la cuenta LMS - **lms_provider**: Proveedor LMS (moodle, canvas, etc.)
     * Register Lms Credentials
     */
    async registerLmsCredentialsApiV1UsersLmsCredentialsPost(requestParameters: RegisterLmsCredentialsApiV1UsersLmsCredentialsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LMSCredentialResponse> {
        const response = await this.registerLmsCredentialsApiV1UsersLmsCredentialsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for syncLmsDataApiV1UsersLmsSyncUserIdPost without sending the request
     */
    async syncLmsDataApiV1UsersLmsSyncUserIdPostRequestOpts(requestParameters: SyncLmsDataApiV1UsersLmsSyncUserIdPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling syncLmsDataApiV1UsersLmsSyncUserIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/lms/sync/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sincronizar datos entre LMS y la plataforma.  Importa usuarios, cursos y calificaciones desde el LMS o exporta progreso de estudiantes al LMS.
     * Sync Lms Data
     */
    async syncLmsDataApiV1UsersLmsSyncUserIdPostRaw(requestParameters: SyncLmsDataApiV1UsersLmsSyncUserIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncResultResponse>> {
        const requestOptions = await this.syncLmsDataApiV1UsersLmsSyncUserIdPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SyncResultResponseFromJSON(jsonValue));
    }

    /**
     * Sincronizar datos entre LMS y la plataforma.  Importa usuarios, cursos y calificaciones desde el LMS o exporta progreso de estudiantes al LMS.
     * Sync Lms Data
     */
    async syncLmsDataApiV1UsersLmsSyncUserIdPost(requestParameters: SyncLmsDataApiV1UsersLmsSyncUserIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncResultResponse> {
        const response = await this.syncLmsDataApiV1UsersLmsSyncUserIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateStudentApiV1UsersStudentsIdPut without sending the request
     */
    async updateStudentApiV1UsersStudentsIdPutRequestOpts(requestParameters: UpdateStudentApiV1UsersStudentsIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateStudentApiV1UsersStudentsIdPut().'
            );
        }

        if (requestParameters['studentUpdate'] == null) {
            throw new runtime.RequiredError(
                'studentUpdate',
                'Required parameter "studentUpdate" was null or undefined when calling updateStudentApiV1UsersStudentsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/students/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StudentUpdateToJSON(requestParameters['studentUpdate']),
        };
    }

    /**
     * Actualizar información del estudiante.  Requiere autenticación y rol de professor o admin.
     * Update Student
     */
    async updateStudentApiV1UsersStudentsIdPutRaw(requestParameters: UpdateStudentApiV1UsersStudentsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentResponse>> {
        const requestOptions = await this.updateStudentApiV1UsersStudentsIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentResponseFromJSON(jsonValue));
    }

    /**
     * Actualizar información del estudiante.  Requiere autenticación y rol de professor o admin.
     * Update Student
     */
    async updateStudentApiV1UsersStudentsIdPut(requestParameters: UpdateStudentApiV1UsersStudentsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentResponse> {
        const response = await this.updateStudentApiV1UsersStudentsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTeacherProfileApiV1UsersProfessorsMePut without sending the request
     */
    async updateTeacherProfileApiV1UsersProfessorsMePutRequestOpts(requestParameters: UpdateTeacherProfileApiV1UsersProfessorsMePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teacherProfileUpdate'] == null) {
            throw new runtime.RequiredError(
                'teacherProfileUpdate',
                'Required parameter "teacherProfileUpdate" was null or undefined when calling updateTeacherProfileApiV1UsersProfessorsMePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/professors/me`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TeacherProfileUpdateToJSON(requestParameters['teacherProfileUpdate']),
        };
    }

    /**
     * Actualizar perfil del profesor autenticado.  Requiere autenticación mediante token JWT.
     * Update Teacher Profile
     */
    async updateTeacherProfileApiV1UsersProfessorsMePutRaw(requestParameters: UpdateTeacherProfileApiV1UsersProfessorsMePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeacherUpdateResponseSchema>> {
        const requestOptions = await this.updateTeacherProfileApiV1UsersProfessorsMePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeacherUpdateResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Actualizar perfil del profesor autenticado.  Requiere autenticación mediante token JWT.
     * Update Teacher Profile
     */
    async updateTeacherProfileApiV1UsersProfessorsMePut(requestParameters: UpdateTeacherProfileApiV1UsersProfessorsMePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeacherUpdateResponseSchema> {
        const response = await this.updateTeacherProfileApiV1UsersProfessorsMePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTeacherSettingsApiV1UsersProfessorsSettingsPut without sending the request
     */
    async updateTeacherSettingsApiV1UsersProfessorsSettingsPutRequestOpts(requestParameters: UpdateTeacherSettingsApiV1UsersProfessorsSettingsPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teacherSettingsUpdate'] == null) {
            throw new runtime.RequiredError(
                'teacherSettingsUpdate',
                'Required parameter "teacherSettingsUpdate" was null or undefined when calling updateTeacherSettingsApiV1UsersProfessorsSettingsPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/professors/settings`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TeacherSettingsUpdateToJSON(requestParameters['teacherSettingsUpdate']),
        };
    }

    /**
     * Actualizar configuraciones del dashboard del profesor.  Requiere autenticación mediante token JWT.
     * Update Teacher Settings
     */
    async updateTeacherSettingsApiV1UsersProfessorsSettingsPutRaw(requestParameters: UpdateTeacherSettingsApiV1UsersProfessorsSettingsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeacherSettingsResponseSchema>> {
        const requestOptions = await this.updateTeacherSettingsApiV1UsersProfessorsSettingsPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeacherSettingsResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Actualizar configuraciones del dashboard del profesor.  Requiere autenticación mediante token JWT.
     * Update Teacher Settings
     */
    async updateTeacherSettingsApiV1UsersProfessorsSettingsPut(requestParameters: UpdateTeacherSettingsApiV1UsersProfessorsSettingsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeacherSettingsResponseSchema> {
        const response = await this.updateTeacherSettingsApiV1UsersProfessorsSettingsPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
