/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  XAPIStatementBatchCreate,
  XAPIStatementListResponse,
  XAPIStatementResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    XAPIStatementBatchCreateFromJSON,
    XAPIStatementBatchCreateToJSON,
    XAPIStatementListResponseFromJSON,
    XAPIStatementListResponseToJSON,
    XAPIStatementResponseFromJSON,
    XAPIStatementResponseToJSON,
} from '../models/index';

export interface GetStatementApiV1StatisticXapiStatementsStatementIdGetRequest {
    statementId: string;
}

export interface GetStatementsApiV1StatisticXapiStatementsGetRequest {
    skip?: number;
    limit?: number;
    studentId?: number | null;
    verbId?: string | null;
    gameId?: number | null;
    levelId?: number | null;
}

export interface SendStatementsApiV1StatisticXapiStatementsPostRequest {
    xAPIStatementBatchCreate: XAPIStatementBatchCreate;
}

/**
 * 
 */
export class XAPIApi extends runtime.BaseAPI {

    /**
     * Creates request options for getStatementApiV1StatisticXapiStatementsStatementIdGet without sending the request
     */
    async getStatementApiV1StatisticXapiStatementsStatementIdGetRequestOpts(requestParameters: GetStatementApiV1StatisticXapiStatementsStatementIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['statementId'] == null) {
            throw new runtime.RequiredError(
                'statementId',
                'Required parameter "statementId" was null or undefined when calling getStatementApiV1StatisticXapiStatementsStatementIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/xapi/statements/{statement_id}`;
        urlPath = urlPath.replace(`{${"statement_id"}}`, encodeURIComponent(String(requestParameters['statementId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a specific xAPI statement by ID.
     * Get Statement
     */
    async getStatementApiV1StatisticXapiStatementsStatementIdGetRaw(requestParameters: GetStatementApiV1StatisticXapiStatementsStatementIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<XAPIStatementResponse>> {
        const requestOptions = await this.getStatementApiV1StatisticXapiStatementsStatementIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => XAPIStatementResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific xAPI statement by ID.
     * Get Statement
     */
    async getStatementApiV1StatisticXapiStatementsStatementIdGet(requestParameters: GetStatementApiV1StatisticXapiStatementsStatementIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<XAPIStatementResponse> {
        const response = await this.getStatementApiV1StatisticXapiStatementsStatementIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStatementsApiV1StatisticXapiStatementsGet without sending the request
     */
    async getStatementsApiV1StatisticXapiStatementsGetRequestOpts(requestParameters: GetStatementsApiV1StatisticXapiStatementsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['studentId'] != null) {
            queryParameters['student_id'] = requestParameters['studentId'];
        }

        if (requestParameters['verbId'] != null) {
            queryParameters['verb_id'] = requestParameters['verbId'];
        }

        if (requestParameters['gameId'] != null) {
            queryParameters['game_id'] = requestParameters['gameId'];
        }

        if (requestParameters['levelId'] != null) {
            queryParameters['level_id'] = requestParameters['levelId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/xapi/statements`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get xAPI statements with optional filters.  Returns statements with pagination. Use filters to narrow results.
     * Get Statements
     */
    async getStatementsApiV1StatisticXapiStatementsGetRaw(requestParameters: GetStatementsApiV1StatisticXapiStatementsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<XAPIStatementListResponse>> {
        const requestOptions = await this.getStatementsApiV1StatisticXapiStatementsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => XAPIStatementListResponseFromJSON(jsonValue));
    }

    /**
     * Get xAPI statements with optional filters.  Returns statements with pagination. Use filters to narrow results.
     * Get Statements
     */
    async getStatementsApiV1StatisticXapiStatementsGet(requestParameters: GetStatementsApiV1StatisticXapiStatementsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<XAPIStatementListResponse> {
        const response = await this.getStatementsApiV1StatisticXapiStatementsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendStatementsApiV1StatisticXapiStatementsPost without sending the request
     */
    async sendStatementsApiV1StatisticXapiStatementsPostRequestOpts(requestParameters: SendStatementsApiV1StatisticXapiStatementsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xAPIStatementBatchCreate'] == null) {
            throw new runtime.RequiredError(
                'xAPIStatementBatchCreate',
                'Required parameter "xAPIStatementBatchCreate" was null or undefined when calling sendStatementsApiV1StatisticXapiStatementsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/statistic/xapi/statements`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: XAPIStatementBatchCreateToJSON(requestParameters['xAPIStatementBatchCreate']),
        };
    }

    /**
     * Receive and store xAPI statements.  Accepts a batch of xAPI statements (1-1000 per request). Supports full xAPI 1.0 specification with game-specific context.  The game client should send statements with: - actor.account.name = student_id - verb = standard xAPI verb - object.id = activity ID (e.g., hello-world://segment/level_1_seg_3) - result = quantitative data (score, success, completion) - context = qualitative data (platform, language, extensions) - context.extensions = game-specific data (game_id, level_id, segment_id)
     * Send Statements
     */
    async sendStatementsApiV1StatisticXapiStatementsPostRaw(requestParameters: SendStatementsApiV1StatisticXapiStatementsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<XAPIStatementResponse>>> {
        const requestOptions = await this.sendStatementsApiV1StatisticXapiStatementsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(XAPIStatementResponseFromJSON));
    }

    /**
     * Receive and store xAPI statements.  Accepts a batch of xAPI statements (1-1000 per request). Supports full xAPI 1.0 specification with game-specific context.  The game client should send statements with: - actor.account.name = student_id - verb = standard xAPI verb - object.id = activity ID (e.g., hello-world://segment/level_1_seg_3) - result = quantitative data (score, success, completion) - context = qualitative data (platform, language, extensions) - context.extensions = game-specific data (game_id, level_id, segment_id)
     * Send Statements
     */
    async sendStatementsApiV1StatisticXapiStatementsPost(requestParameters: SendStatementsApiV1StatisticXapiStatementsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<XAPIStatementResponse>> {
        const response = await this.sendStatementsApiV1StatisticXapiStatementsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
