/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackCreate
 */
export interface FeedbackCreate {
    /**
     * 
     * @type {string}
     * @memberof FeedbackCreate
     */
    comments: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackCreate
     */
    rating?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FeedbackCreate
     */
    student_id: number;
}

/**
 * Check if a given object implements the FeedbackCreate interface.
 */
export function instanceOfFeedbackCreate(value: object): value is FeedbackCreate {
    if (!('comments' in value) || value['comments'] === undefined) return false;
    if (!('student_id' in value) || value['student_id'] === undefined) return false;
    return true;
}

export function FeedbackCreateFromJSON(json: any): FeedbackCreate {
    return FeedbackCreateFromJSONTyped(json, false);
}

export function FeedbackCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': json['comments'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'student_id': json['student_id'],
    };
}

export function FeedbackCreateToJSON(json: any): FeedbackCreate {
    return FeedbackCreateToJSONTyped(json, false);
}

export function FeedbackCreateToJSONTyped(value?: FeedbackCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comments': value['comments'],
        'rating': value['rating'],
        'student_id': value['student_id'],
    };
}

