/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para crear una nueva instancia de juego
 * @export
 * @interface GameInstanceCreate
 */
export interface GameInstanceCreate {
    /**
     * 
     * @type {number}
     * @memberof GameInstanceCreate
     */
    game_id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GameInstanceCreate
     */
    status?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceCreate
     */
    student_id: number;
}

/**
 * Check if a given object implements the GameInstanceCreate interface.
 */
export function instanceOfGameInstanceCreate(value: object): value is GameInstanceCreate {
    if (!('student_id' in value) || value['student_id'] === undefined) return false;
    return true;
}

export function GameInstanceCreateFromJSON(json: any): GameInstanceCreate {
    return GameInstanceCreateFromJSONTyped(json, false);
}

export function GameInstanceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameInstanceCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'game_id': json['game_id'] == null ? undefined : json['game_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'student_id': json['student_id'],
    };
}

export function GameInstanceCreateToJSON(json: any): GameInstanceCreate {
    return GameInstanceCreateToJSONTyped(json, false);
}

export function GameInstanceCreateToJSONTyped(value?: GameInstanceCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'game_id': value['game_id'],
        'status': value['status'],
        'student_id': value['student_id'],
    };
}

