/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para la respuesta de una instancia de juego
 * @export
 * @interface GameInstanceResponse
 */
export interface GameInstanceResponse {
    /**
     * 
     * @type {number}
     * @memberof GameInstanceResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceResponse
     */
    gameId: number;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceResponse
     */
    studentId: number;
    /**
     * 
     * @type {string}
     * @memberof GameInstanceResponse
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof GameInstanceResponse
     */
    startInstance: Date;
    /**
     * 
     * @type {Date}
     * @memberof GameInstanceResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GameInstanceResponse
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof GameInstanceResponse
     */
    isDeleted?: boolean;
}

/**
 * Check if a given object implements the GameInstanceResponse interface.
 */
export function instanceOfGameInstanceResponse(value: object): value is GameInstanceResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('gameId' in value) || value['gameId'] === undefined) return false;
    if (!('studentId' in value) || value['studentId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('startInstance' in value) || value['startInstance'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function GameInstanceResponseFromJSON(json: any): GameInstanceResponse {
    return GameInstanceResponseFromJSONTyped(json, false);
}

export function GameInstanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameInstanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'gameId': json['game_id'],
        'studentId': json['student_id'],
        'status': json['status'],
        'startInstance': (new Date(json['start_instance'])),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'isDeleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
    };
}

export function GameInstanceResponseToJSON(json: any): GameInstanceResponse {
    return GameInstanceResponseToJSONTyped(json, false);
}

export function GameInstanceResponseToJSONTyped(value?: GameInstanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'game_id': value['gameId'],
        'student_id': value['studentId'],
        'status': value['status'],
        'start_instance': value['startInstance'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'is_deleted': value['isDeleted'],
    };
}

