/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameResponse } from './GameResponse';
import {
    GameResponseFromJSON,
    GameResponseFromJSONTyped,
    GameResponseToJSON,
    GameResponseToJSONTyped,
} from './GameResponse';

/**
 * Esquema para respuesta de creación de juego
 * @export
 * @interface GameCreateResponse
 */
export interface GameCreateResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GameCreateResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameCreateResponse
     */
    message?: string;
    /**
     * 
     * @type {GameResponse}
     * @memberof GameCreateResponse
     */
    data: GameResponse;
}

/**
 * Check if a given object implements the GameCreateResponse interface.
 */
export function instanceOfGameCreateResponse(value: object): value is GameCreateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GameCreateResponseFromJSON(json: any): GameCreateResponse {
    return GameCreateResponseFromJSONTyped(json, false);
}

export function GameCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': GameResponseFromJSON(json['data']),
    };
}

export function GameCreateResponseToJSON(json: any): GameCreateResponse {
    return GameCreateResponseToJSONTyped(json, false);
}

export function GameCreateResponseToJSONTyped(value?: GameCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': GameResponseToJSON(value['data']),
    };
}

