/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameInstanceResponse } from './GameInstanceResponse';
import {
    GameInstanceResponseFromJSON,
    GameInstanceResponseFromJSONTyped,
    GameInstanceResponseToJSON,
    GameInstanceResponseToJSONTyped,
} from './GameInstanceResponse';

/**
 * Esquema para respuesta de finalización de instancia
 * @export
 * @interface GameInstanceEndResponse
 */
export interface GameInstanceEndResponse {
    /**
     * 
     * @type {GameInstanceResponse}
     * @memberof GameInstanceEndResponse
     */
    data: GameInstanceResponse;
    /**
     * 
     * @type {string}
     * @memberof GameInstanceEndResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameInstanceEndResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the GameInstanceEndResponse interface.
 */
export function instanceOfGameInstanceEndResponse(value: object): value is GameInstanceEndResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GameInstanceEndResponseFromJSON(json: any): GameInstanceEndResponse {
    return GameInstanceEndResponseFromJSONTyped(json, false);
}

export function GameInstanceEndResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameInstanceEndResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GameInstanceResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function GameInstanceEndResponseToJSON(json: any): GameInstanceEndResponse {
    return GameInstanceEndResponseToJSONTyped(json, false);
}

export function GameInstanceEndResponseToJSONTyped(value?: GameInstanceEndResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GameInstanceResponseToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

