/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameResponse } from './GameResponse';
import {
    GameResponseFromJSON,
    GameResponseFromJSONTyped,
    GameResponseToJSON,
    GameResponseToJSONTyped,
} from './GameResponse';

/**
 * Esquema para respuesta de actualización de juego
 * @export
 * @interface GameUpdateResponse
 */
export interface GameUpdateResponse {
    /**
     * 
     * @type {GameResponse}
     * @memberof GameUpdateResponse
     */
    data: GameResponse;
    /**
     * 
     * @type {string}
     * @memberof GameUpdateResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameUpdateResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the GameUpdateResponse interface.
 */
export function instanceOfGameUpdateResponse(value: object): value is GameUpdateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GameUpdateResponseFromJSON(json: any): GameUpdateResponse {
    return GameUpdateResponseFromJSONTyped(json, false);
}

export function GameUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GameResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function GameUpdateResponseToJSON(json: any): GameUpdateResponse {
    return GameUpdateResponseToJSONTyped(json, false);
}

export function GameUpdateResponseToJSONTyped(value?: GameUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GameResponseToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

