/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta detallada de juego con relaciones
 * @export
 * @interface GameDetailResponse
 */
export interface GameDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof GameDetailResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof GameDetailResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameDetailResponse
     */
    creator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameDetailResponse
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameDetailResponse
     */
    publicationStatus?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GameDetailResponse
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof GameDetailResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GameDetailResponse
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof GameDetailResponse
     */
    isDeleted?: boolean;
    /**
     * Cantidad de niveles del juego
     * @type {number}
     * @memberof GameDetailResponse
     */
    levelsCount?: number;
}

/**
 * Check if a given object implements the GameDetailResponse interface.
 */
export function instanceOfGameDetailResponse(value: object): value is GameDetailResponse {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function GameDetailResponseFromJSON(json: any): GameDetailResponse {
    return GameDetailResponseFromJSONTyped(json, false);
}

export function GameDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'creator': json['creator'] == null ? undefined : json['creator'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'publicationStatus': json['publication_status'] == null ? undefined : json['publication_status'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'isDeleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
        'levelsCount': json['levels_count'] == null ? undefined : json['levels_count'],
    };
}

export function GameDetailResponseToJSON(json: any): GameDetailResponse {
    return GameDetailResponseToJSONTyped(json, false);
}

export function GameDetailResponseToJSONTyped(value?: GameDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'creator': value['creator'],
        'subject': value['subject'],
        'publication_status': value['publicationStatus'],
        'id': value['id'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'is_deleted': value['isDeleted'],
        'levels_count': value['levelsCount'],
    };
}

