/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameInstanceResponse } from './GameInstanceResponse';
import {
    GameInstanceResponseFromJSON,
    GameInstanceResponseFromJSONTyped,
    GameInstanceResponseToJSON,
    GameInstanceResponseToJSONTyped,
} from './GameInstanceResponse';

/**
 * Esquema para listado de instancias de juego
 * @export
 * @interface GameInstanceListResponse
 */
export interface GameInstanceListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GameInstanceListResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameInstanceListResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<GameInstanceResponse>}
     * @memberof GameInstanceListResponse
     */
    data?: Array<GameInstanceResponse>;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceListResponse
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceListResponse
     */
    skip?: number;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceListResponse
     */
    limit?: number;
}

/**
 * Check if a given object implements the GameInstanceListResponse interface.
 */
export function instanceOfGameInstanceListResponse(value: object): value is GameInstanceListResponse {
    return true;
}

export function GameInstanceListResponseFromJSON(json: any): GameInstanceListResponse {
    return GameInstanceListResponseFromJSONTyped(json, false);
}

export function GameInstanceListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameInstanceListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GameInstanceResponseFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'skip': json['skip'] == null ? undefined : json['skip'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function GameInstanceListResponseToJSON(json: any): GameInstanceListResponse {
    return GameInstanceListResponseToJSONTyped(json, false);
}

export function GameInstanceListResponseToJSONTyped(value?: GameInstanceListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GameInstanceResponseToJSON)),
        'total': value['total'],
        'skip': value['skip'],
        'limit': value['limit'],
    };
}

