/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para la respuesta de una instancia de juego
 * @export
 * @interface GameInstanceResponse
 */
export interface GameInstanceResponse {
    /**
     * 
     * @type {Date}
     * @memberof GameInstanceResponse
     */
    created_at: Date;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceResponse
     */
    game_id: number;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceResponse
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof GameInstanceResponse
     */
    is_deleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof GameInstanceResponse
     */
    start_instance: Date;
    /**
     * 
     * @type {string}
     * @memberof GameInstanceResponse
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceResponse
     */
    student_id: number;
    /**
     * 
     * @type {Date}
     * @memberof GameInstanceResponse
     */
    updated_at?: Date | null;
}

/**
 * Check if a given object implements the GameInstanceResponse interface.
 */
export function instanceOfGameInstanceResponse(value: object): value is GameInstanceResponse {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('game_id' in value) || value['game_id'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('start_instance' in value) || value['start_instance'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('student_id' in value) || value['student_id'] === undefined) return false;
    return true;
}

export function GameInstanceResponseFromJSON(json: any): GameInstanceResponse {
    return GameInstanceResponseFromJSONTyped(json, false);
}

export function GameInstanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameInstanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': (new Date(json['created_at'])),
        'game_id': json['game_id'],
        'id': json['id'],
        'is_deleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
        'start_instance': (new Date(json['start_instance'])),
        'status': json['status'],
        'student_id': json['student_id'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function GameInstanceResponseToJSON(json: any): GameInstanceResponse {
    return GameInstanceResponseToJSONTyped(json, false);
}

export function GameInstanceResponseToJSONTyped(value?: GameInstanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'].toISOString(),
        'game_id': value['game_id'],
        'id': value['id'],
        'is_deleted': value['is_deleted'],
        'start_instance': value['start_instance'].toISOString(),
        'status': value['status'],
        'student_id': value['student_id'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

