/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta de eliminación de juego
 * @export
 * @interface GameDeleteResponse
 */
export interface GameDeleteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GameDeleteResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameDeleteResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the GameDeleteResponse interface.
 */
export function instanceOfGameDeleteResponse(value: object): value is GameDeleteResponse {
    return true;
}

export function GameDeleteResponseFromJSON(json: any): GameDeleteResponse {
    return GameDeleteResponseFromJSONTyped(json, false);
}

export function GameDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GameDeleteResponseToJSON(json: any): GameDeleteResponse {
    return GameDeleteResponseToJSONTyped(json, false);
}

export function GameDeleteResponseToJSONTyped(value?: GameDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

