/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameInstanceResponse } from './GameInstanceResponse';
import {
    GameInstanceResponseFromJSON,
    GameInstanceResponseFromJSONTyped,
    GameInstanceResponseToJSON,
    GameInstanceResponseToJSONTyped,
} from './GameInstanceResponse';

/**
 * Esquema para respuesta de creación de instancia
 * @export
 * @interface GameInstanceCreateResponse
 */
export interface GameInstanceCreateResponse {
    /**
     * 
     * @type {GameInstanceResponse}
     * @memberof GameInstanceCreateResponse
     */
    data: GameInstanceResponse;
    /**
     * 
     * @type {string}
     * @memberof GameInstanceCreateResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameInstanceCreateResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the GameInstanceCreateResponse interface.
 */
export function instanceOfGameInstanceCreateResponse(value: object): value is GameInstanceCreateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GameInstanceCreateResponseFromJSON(json: any): GameInstanceCreateResponse {
    return GameInstanceCreateResponseFromJSONTyped(json, false);
}

export function GameInstanceCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameInstanceCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GameInstanceResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function GameInstanceCreateResponseToJSON(json: any): GameInstanceCreateResponse {
    return GameInstanceCreateResponseToJSONTyped(json, false);
}

export function GameInstanceCreateResponseToJSONTyped(value?: GameInstanceCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GameInstanceResponseToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

