/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta detallada de instancia con relaciones
 * @export
 * @interface GameInstanceDetailResponse
 */
export interface GameInstanceDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof GameInstanceDetailResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceDetailResponse
     */
    gameId: number;
    /**
     * 
     * @type {number}
     * @memberof GameInstanceDetailResponse
     */
    studentId: number;
    /**
     * 
     * @type {string}
     * @memberof GameInstanceDetailResponse
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof GameInstanceDetailResponse
     */
    startInstance: Date;
    /**
     * 
     * @type {Date}
     * @memberof GameInstanceDetailResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GameInstanceDetailResponse
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof GameInstanceDetailResponse
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameInstanceDetailResponse
     */
    gameTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameInstanceDetailResponse
     */
    studentUsername?: string | null;
}

/**
 * Check if a given object implements the GameInstanceDetailResponse interface.
 */
export function instanceOfGameInstanceDetailResponse(value: object): value is GameInstanceDetailResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('gameId' in value) || value['gameId'] === undefined) return false;
    if (!('studentId' in value) || value['studentId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('startInstance' in value) || value['startInstance'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function GameInstanceDetailResponseFromJSON(json: any): GameInstanceDetailResponse {
    return GameInstanceDetailResponseFromJSONTyped(json, false);
}

export function GameInstanceDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameInstanceDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'gameId': json['game_id'],
        'studentId': json['student_id'],
        'status': json['status'],
        'startInstance': (new Date(json['start_instance'])),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'isDeleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
        'gameTitle': json['game_title'] == null ? undefined : json['game_title'],
        'studentUsername': json['student_username'] == null ? undefined : json['student_username'],
    };
}

export function GameInstanceDetailResponseToJSON(json: any): GameInstanceDetailResponse {
    return GameInstanceDetailResponseToJSONTyped(json, false);
}

export function GameInstanceDetailResponseToJSONTyped(value?: GameInstanceDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'game_id': value['gameId'],
        'student_id': value['studentId'],
        'status': value['status'],
        'start_instance': value['startInstance'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'is_deleted': value['isDeleted'],
        'game_title': value['gameTitle'],
        'student_username': value['studentUsername'],
    };
}

