/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameResponse } from './GameResponse';
import {
    GameResponseFromJSON,
    GameResponseFromJSONTyped,
    GameResponseToJSON,
    GameResponseToJSONTyped,
} from './GameResponse';

/**
 * Esquema para listado de juegos
 * @export
 * @interface GameListResponse
 */
export interface GameListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GameListResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameListResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<GameResponse>}
     * @memberof GameListResponse
     */
    data?: Array<GameResponse>;
    /**
     * 
     * @type {number}
     * @memberof GameListResponse
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof GameListResponse
     */
    skip?: number;
    /**
     * 
     * @type {number}
     * @memberof GameListResponse
     */
    limit?: number;
}

/**
 * Check if a given object implements the GameListResponse interface.
 */
export function instanceOfGameListResponse(value: object): value is GameListResponse {
    return true;
}

export function GameListResponseFromJSON(json: any): GameListResponse {
    return GameListResponseFromJSONTyped(json, false);
}

export function GameListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GameResponseFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'skip': json['skip'] == null ? undefined : json['skip'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function GameListResponseToJSON(json: any): GameListResponse {
    return GameListResponseToJSONTyped(json, false);
}

export function GameListResponseToJSONTyped(value?: GameListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GameResponseToJSON)),
        'total': value['total'],
        'skip': value['skip'],
        'limit': value['limit'],
    };
}

