/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para creación de juego
 * @export
 * @interface GameCreate
 */
export interface GameCreate {
    /**
     * 
     * @type {string}
     * @memberof GameCreate
     */
    creator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameCreate
     */
    publication_status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameCreate
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameCreate
     */
    title: string;
}

/**
 * Check if a given object implements the GameCreate interface.
 */
export function instanceOfGameCreate(value: object): value is GameCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function GameCreateFromJSON(json: any): GameCreate {
    return GameCreateFromJSONTyped(json, false);
}

export function GameCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'creator': json['creator'] == null ? undefined : json['creator'],
        'description': json['description'] == null ? undefined : json['description'],
        'publication_status': json['publication_status'] == null ? undefined : json['publication_status'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'title': json['title'],
    };
}

export function GameCreateToJSON(json: any): GameCreate {
    return GameCreateToJSONTyped(json, false);
}

export function GameCreateToJSONTyped(value?: GameCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creator': value['creator'],
        'description': value['description'],
        'publication_status': value['publication_status'],
        'subject': value['subject'],
        'title': value['title'],
    };
}

