/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta de juego
 * @export
 * @interface GameResponse
 */
export interface GameResponse {
    /**
     * 
     * @type {Date}
     * @memberof GameResponse
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof GameResponse
     */
    creator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameResponse
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GameResponse
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof GameResponse
     */
    is_deleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameResponse
     */
    publication_status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameResponse
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameResponse
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof GameResponse
     */
    updated_at?: Date | null;
}

/**
 * Check if a given object implements the GameResponse interface.
 */
export function instanceOfGameResponse(value: object): value is GameResponse {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function GameResponseFromJSON(json: any): GameResponse {
    return GameResponseFromJSONTyped(json, false);
}

export function GameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': (new Date(json['created_at'])),
        'creator': json['creator'] == null ? undefined : json['creator'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'is_deleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
        'publication_status': json['publication_status'] == null ? undefined : json['publication_status'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'title': json['title'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function GameResponseToJSON(json: any): GameResponse {
    return GameResponseToJSONTyped(json, false);
}

export function GameResponseToJSONTyped(value?: GameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'].toISOString(),
        'creator': value['creator'],
        'description': value['description'],
        'id': value['id'],
        'is_deleted': value['is_deleted'],
        'publication_status': value['publication_status'],
        'subject': value['subject'],
        'title': value['title'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

