/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para actualización de juego
 * @export
 * @interface GameUpdate
 */
export interface GameUpdate {
    /**
     * 
     * @type {string}
     * @memberof GameUpdate
     */
    creator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameUpdate
     */
    publication_status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameUpdate
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameUpdate
     */
    title?: string | null;
}

/**
 * Check if a given object implements the GameUpdate interface.
 */
export function instanceOfGameUpdate(value: object): value is GameUpdate {
    return true;
}

export function GameUpdateFromJSON(json: any): GameUpdate {
    return GameUpdateFromJSONTyped(json, false);
}

export function GameUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'creator': json['creator'] == null ? undefined : json['creator'],
        'description': json['description'] == null ? undefined : json['description'],
        'publication_status': json['publication_status'] == null ? undefined : json['publication_status'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function GameUpdateToJSON(json: any): GameUpdate {
    return GameUpdateToJSONTyped(json, false);
}

export function GameUpdateToJSONTyped(value?: GameUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creator': value['creator'],
        'description': value['description'],
        'publication_status': value['publication_status'],
        'subject': value['subject'],
        'title': value['title'],
    };
}

