/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta de nivel
 * @export
 * @interface LevelResponse
 */
export interface LevelResponse {
    /**
     * 
     * @type {number}
     * @memberof LevelResponse
     */
    levelNumber: number;
    /**
     * 
     * @type {string}
     * @memberof LevelResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof LevelResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LevelResponse
     */
    goal?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LevelResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof LevelResponse
     */
    gameId: number;
    /**
     * 
     * @type {Date}
     * @memberof LevelResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof LevelResponse
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof LevelResponse
     */
    isDeleted?: boolean;
}

/**
 * Check if a given object implements the LevelResponse interface.
 */
export function instanceOfLevelResponse(value: object): value is LevelResponse {
    if (!('levelNumber' in value) || value['levelNumber'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('gameId' in value) || value['gameId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function LevelResponseFromJSON(json: any): LevelResponse {
    return LevelResponseFromJSONTyped(json, false);
}

export function LevelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LevelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'levelNumber': json['level_number'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'goal': json['goal'] == null ? undefined : json['goal'],
        'id': json['id'],
        'gameId': json['game_id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'isDeleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
    };
}

export function LevelResponseToJSON(json: any): LevelResponse {
    return LevelResponseToJSONTyped(json, false);
}

export function LevelResponseToJSONTyped(value?: LevelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level_number': value['levelNumber'],
        'title': value['title'],
        'description': value['description'],
        'goal': value['goal'],
        'id': value['id'],
        'game_id': value['gameId'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'is_deleted': value['isDeleted'],
    };
}

