/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para creación de nivel
 * @export
 * @interface LevelCreate
 */
export interface LevelCreate {
    /**
     * 
     * @type {number}
     * @memberof LevelCreate
     */
    levelNumber: number;
    /**
     * 
     * @type {string}
     * @memberof LevelCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof LevelCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LevelCreate
     */
    goal?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LevelCreate
     */
    gameId?: number | null;
}

/**
 * Check if a given object implements the LevelCreate interface.
 */
export function instanceOfLevelCreate(value: object): value is LevelCreate {
    if (!('levelNumber' in value) || value['levelNumber'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function LevelCreateFromJSON(json: any): LevelCreate {
    return LevelCreateFromJSONTyped(json, false);
}

export function LevelCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LevelCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'levelNumber': json['level_number'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'goal': json['goal'] == null ? undefined : json['goal'],
        'gameId': json['game_id'] == null ? undefined : json['game_id'],
    };
}

export function LevelCreateToJSON(json: any): LevelCreate {
    return LevelCreateToJSONTyped(json, false);
}

export function LevelCreateToJSONTyped(value?: LevelCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level_number': value['levelNumber'],
        'title': value['title'],
        'description': value['description'],
        'goal': value['goal'],
        'game_id': value['gameId'],
    };
}

