/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para actualización de nivel
 * @export
 * @interface LevelUpdate
 */
export interface LevelUpdate {
    /**
     * 
     * @type {number}
     * @memberof LevelUpdate
     */
    levelNumber?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LevelUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LevelUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LevelUpdate
     */
    goal?: string | null;
}

/**
 * Check if a given object implements the LevelUpdate interface.
 */
export function instanceOfLevelUpdate(value: object): value is LevelUpdate {
    return true;
}

export function LevelUpdateFromJSON(json: any): LevelUpdate {
    return LevelUpdateFromJSONTyped(json, false);
}

export function LevelUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LevelUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'levelNumber': json['level_number'] == null ? undefined : json['level_number'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'goal': json['goal'] == null ? undefined : json['goal'],
    };
}

export function LevelUpdateToJSON(json: any): LevelUpdate {
    return LevelUpdateToJSONTyped(json, false);
}

export function LevelUpdateToJSONTyped(value?: LevelUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level_number': value['levelNumber'],
        'title': value['title'],
        'description': value['description'],
        'goal': value['goal'],
    };
}

