/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LevelResponse } from './LevelResponse';
import {
    LevelResponseFromJSON,
    LevelResponseFromJSONTyped,
    LevelResponseToJSON,
    LevelResponseToJSONTyped,
} from './LevelResponse';

/**
 * Esquema para respuesta de creación de nivel
 * @export
 * @interface LevelCreateResponse
 */
export interface LevelCreateResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LevelCreateResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LevelCreateResponse
     */
    message?: string;
    /**
     * 
     * @type {LevelResponse}
     * @memberof LevelCreateResponse
     */
    data: LevelResponse;
}

/**
 * Check if a given object implements the LevelCreateResponse interface.
 */
export function instanceOfLevelCreateResponse(value: object): value is LevelCreateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function LevelCreateResponseFromJSON(json: any): LevelCreateResponse {
    return LevelCreateResponseFromJSONTyped(json, false);
}

export function LevelCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LevelCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': LevelResponseFromJSON(json['data']),
    };
}

export function LevelCreateResponseToJSON(json: any): LevelCreateResponse {
    return LevelCreateResponseToJSONTyped(json, false);
}

export function LevelCreateResponseToJSONTyped(value?: LevelCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': LevelResponseToJSON(value['data']),
    };
}

