/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta de eliminación de nivel
 * @export
 * @interface LevelDeleteResponse
 */
export interface LevelDeleteResponse {
    /**
     * 
     * @type {string}
     * @memberof LevelDeleteResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LevelDeleteResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the LevelDeleteResponse interface.
 */
export function instanceOfLevelDeleteResponse(value: object): value is LevelDeleteResponse {
    return true;
}

export function LevelDeleteResponseFromJSON(json: any): LevelDeleteResponse {
    return LevelDeleteResponseFromJSONTyped(json, false);
}

export function LevelDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LevelDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function LevelDeleteResponseToJSON(json: any): LevelDeleteResponse {
    return LevelDeleteResponseToJSONTyped(json, false);
}

export function LevelDeleteResponseToJSONTyped(value?: LevelDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
    };
}

