/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LevelResponse } from './LevelResponse';
import {
    LevelResponseFromJSON,
    LevelResponseFromJSONTyped,
    LevelResponseToJSON,
    LevelResponseToJSONTyped,
} from './LevelResponse';

/**
 * Esquema para listado de niveles
 * @export
 * @interface LevelListResponse
 */
export interface LevelListResponse {
    /**
     * 
     * @type {Array<LevelResponse>}
     * @memberof LevelListResponse
     */
    data?: Array<LevelResponse>;
    /**
     * 
     * @type {string}
     * @memberof LevelListResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LevelListResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof LevelListResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the LevelListResponse interface.
 */
export function instanceOfLevelListResponse(value: object): value is LevelListResponse {
    return true;
}

export function LevelListResponseFromJSON(json: any): LevelListResponse {
    return LevelListResponseFromJSONTyped(json, false);
}

export function LevelListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LevelListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(LevelResponseFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function LevelListResponseToJSON(json: any): LevelListResponse {
    return LevelListResponseToJSONTyped(json, false);
}

export function LevelListResponseToJSONTyped(value?: LevelListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(LevelResponseToJSON)),
        'message': value['message'],
        'success': value['success'],
        'total': value['total'],
    };
}

