/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta de nivel
 * @export
 * @interface LevelResponse
 */
export interface LevelResponse {
    /**
     * 
     * @type {Date}
     * @memberof LevelResponse
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof LevelResponse
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LevelResponse
     */
    game_id: number;
    /**
     * 
     * @type {string}
     * @memberof LevelResponse
     */
    goal?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LevelResponse
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof LevelResponse
     */
    is_deleted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof LevelResponse
     */
    level_number: number;
    /**
     * 
     * @type {string}
     * @memberof LevelResponse
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof LevelResponse
     */
    updated_at?: Date | null;
}

/**
 * Check if a given object implements the LevelResponse interface.
 */
export function instanceOfLevelResponse(value: object): value is LevelResponse {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('game_id' in value) || value['game_id'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('level_number' in value) || value['level_number'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function LevelResponseFromJSON(json: any): LevelResponse {
    return LevelResponseFromJSONTyped(json, false);
}

export function LevelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LevelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'game_id': json['game_id'],
        'goal': json['goal'] == null ? undefined : json['goal'],
        'id': json['id'],
        'is_deleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
        'level_number': json['level_number'],
        'title': json['title'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function LevelResponseToJSON(json: any): LevelResponse {
    return LevelResponseToJSONTyped(json, false);
}

export function LevelResponseToJSONTyped(value?: LevelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'].toISOString(),
        'description': value['description'],
        'game_id': value['game_id'],
        'goal': value['goal'],
        'id': value['id'],
        'is_deleted': value['is_deleted'],
        'level_number': value['level_number'],
        'title': value['title'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

