/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for creating LMS credentials.
 * @export
 * @interface LMSCredentialCreate
 */
export interface LMSCredentialCreate {
    /**
     * 
     * @type {number}
     * @memberof LMSCredentialCreate
     */
    userId: number;
    /**
     * URL del LMS (ej: https://moodle.university.edu)
     * @type {string}
     * @memberof LMSCredentialCreate
     */
    lmsUrl: string;
    /**
     * Email de la cuenta en el LMS
     * @type {string}
     * @memberof LMSCredentialCreate
     */
    lmsEmail: string;
    /**
     * Contraseña de la cuenta LMS
     * @type {string}
     * @memberof LMSCredentialCreate
     */
    lmsPassword: string;
    /**
     * Proveedor LMS (moodle, canvas, etc.)
     * @type {string}
     * @memberof LMSCredentialCreate
     */
    lmsProvider: string;
}

/**
 * Check if a given object implements the LMSCredentialCreate interface.
 */
export function instanceOfLMSCredentialCreate(value: object): value is LMSCredentialCreate {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('lmsUrl' in value) || value['lmsUrl'] === undefined) return false;
    if (!('lmsEmail' in value) || value['lmsEmail'] === undefined) return false;
    if (!('lmsPassword' in value) || value['lmsPassword'] === undefined) return false;
    if (!('lmsProvider' in value) || value['lmsProvider'] === undefined) return false;
    return true;
}

export function LMSCredentialCreateFromJSON(json: any): LMSCredentialCreate {
    return LMSCredentialCreateFromJSONTyped(json, false);
}

export function LMSCredentialCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LMSCredentialCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'lmsUrl': json['lms_url'],
        'lmsEmail': json['lms_email'],
        'lmsPassword': json['lms_password'],
        'lmsProvider': json['lms_provider'],
    };
}

export function LMSCredentialCreateToJSON(json: any): LMSCredentialCreate {
    return LMSCredentialCreateToJSONTyped(json, false);
}

export function LMSCredentialCreateToJSONTyped(value?: LMSCredentialCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'lms_url': value['lmsUrl'],
        'lms_email': value['lmsEmail'],
        'lms_password': value['lmsPassword'],
        'lms_provider': value['lmsProvider'],
    };
}

