/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for LMS credential response (password masked).
 * @export
 * @interface LMSCredentialResponse
 */
export interface LMSCredentialResponse {
    /**
     * 
     * @type {string}
     * @memberof LMSCredentialResponse
     */
    access_token?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof LMSCredentialResponse
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof LMSCredentialResponse
     */
    expire_at?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof LMSCredentialResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LMSCredentialResponse
     */
    lms_email: string;
    /**
     * 
     * @type {string}
     * @memberof LMSCredentialResponse
     */
    lms_provider: string;
    /**
     * 
     * @type {string}
     * @memberof LMSCredentialResponse
     */
    lms_url?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof LMSCredentialResponse
     */
    updated_at?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof LMSCredentialResponse
     */
    user_id: number;
}

/**
 * Check if a given object implements the LMSCredentialResponse interface.
 */
export function instanceOfLMSCredentialResponse(value: object): value is LMSCredentialResponse {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lms_email' in value) || value['lms_email'] === undefined) return false;
    if (!('lms_provider' in value) || value['lms_provider'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    return true;
}

export function LMSCredentialResponseFromJSON(json: any): LMSCredentialResponse {
    return LMSCredentialResponseFromJSONTyped(json, false);
}

export function LMSCredentialResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LMSCredentialResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'access_token': json['access_token'] == null ? undefined : json['access_token'],
        'created_at': (new Date(json['created_at'])),
        'expire_at': json['expire_at'] == null ? undefined : (new Date(json['expire_at'])),
        'id': json['id'],
        'lms_email': json['lms_email'],
        'lms_provider': json['lms_provider'],
        'lms_url': json['lms_url'] == null ? undefined : json['lms_url'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'user_id': json['user_id'],
    };
}

export function LMSCredentialResponseToJSON(json: any): LMSCredentialResponse {
    return LMSCredentialResponseToJSONTyped(json, false);
}

export function LMSCredentialResponseToJSONTyped(value?: LMSCredentialResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['access_token'],
        'created_at': value['created_at'].toISOString(),
        'expire_at': value['expire_at'] == null ? value['expire_at'] : value['expire_at'].toISOString(),
        'id': value['id'],
        'lms_email': value['lms_email'],
        'lms_provider': value['lms_provider'],
        'lms_url': value['lms_url'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
        'user_id': value['user_id'],
    };
}

