/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for creating LMS credentials.
 * @export
 * @interface LMSCredentialCreate
 */
export interface LMSCredentialCreate {
    /**
     * Email de la cuenta en el LMS
     * @type {string}
     * @memberof LMSCredentialCreate
     */
    lms_email: string;
    /**
     * Contraseña de la cuenta LMS
     * @type {string}
     * @memberof LMSCredentialCreate
     */
    lms_password: string;
    /**
     * Proveedor LMS (moodle, canvas, etc.)
     * @type {string}
     * @memberof LMSCredentialCreate
     */
    lms_provider: string;
    /**
     * URL del LMS (ej: https://moodle.university.edu)
     * @type {string}
     * @memberof LMSCredentialCreate
     */
    lms_url: string;
    /**
     * 
     * @type {number}
     * @memberof LMSCredentialCreate
     */
    user_id: number;
}

/**
 * Check if a given object implements the LMSCredentialCreate interface.
 */
export function instanceOfLMSCredentialCreate(value: object): value is LMSCredentialCreate {
    if (!('lms_email' in value) || value['lms_email'] === undefined) return false;
    if (!('lms_password' in value) || value['lms_password'] === undefined) return false;
    if (!('lms_provider' in value) || value['lms_provider'] === undefined) return false;
    if (!('lms_url' in value) || value['lms_url'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    return true;
}

export function LMSCredentialCreateFromJSON(json: any): LMSCredentialCreate {
    return LMSCredentialCreateFromJSONTyped(json, false);
}

export function LMSCredentialCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LMSCredentialCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'lms_email': json['lms_email'],
        'lms_password': json['lms_password'],
        'lms_provider': json['lms_provider'],
        'lms_url': json['lms_url'],
        'user_id': json['user_id'],
    };
}

export function LMSCredentialCreateToJSON(json: any): LMSCredentialCreate {
    return LMSCredentialCreateToJSONTyped(json, false);
}

export function LMSCredentialCreateToJSONTyped(value?: LMSCredentialCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lms_email': value['lms_email'],
        'lms_password': value['lms_password'],
        'lms_provider': value['lms_provider'],
        'lms_url': value['lms_url'],
        'user_id': value['user_id'],
    };
}

