/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricTypeCreate
 */
export interface MetricTypeCreate {
    /**
     * 
     * @type {string}
     * @memberof MetricTypeCreate
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof MetricTypeCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetricTypeCreate
     */
    name: string;
}

/**
 * Check if a given object implements the MetricTypeCreate interface.
 */
export function instanceOfMetricTypeCreate(value: object): value is MetricTypeCreate {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MetricTypeCreateFromJSON(json: any): MetricTypeCreate {
    return MetricTypeCreateFromJSONTyped(json, false);
}

export function MetricTypeCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricTypeCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
    };
}

export function MetricTypeCreateToJSON(json: any): MetricTypeCreate {
    return MetricTypeCreateToJSONTyped(json, false);
}

export function MetricTypeCreateToJSONTyped(value?: MetricTypeCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'name': value['name'],
    };
}

