/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricTypeSchema
 */
export interface MetricTypeSchema {
    /**
     * 
     * @type {string}
     * @memberof MetricTypeSchema
     */
    code: string;
    /**
     * 
     * @type {Date}
     * @memberof MetricTypeSchema
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof MetricTypeSchema
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MetricTypeSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MetricTypeSchema
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof MetricTypeSchema
     */
    updated_at?: Date | null;
}

/**
 * Check if a given object implements the MetricTypeSchema interface.
 */
export function instanceOfMetricTypeSchema(value: object): value is MetricTypeSchema {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MetricTypeSchemaFromJSON(json: any): MetricTypeSchema {
    return MetricTypeSchemaFromJSONTyped(json, false);
}

export function MetricTypeSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricTypeSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'created_at': (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'name': json['name'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function MetricTypeSchemaToJSON(json: any): MetricTypeSchema {
    return MetricTypeSchemaToJSONTyped(json, false);
}

export function MetricTypeSchemaToJSONTyped(value?: MetricTypeSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'created_at': value['created_at'].toISOString(),
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

