/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SegmentLevelResponse } from './SegmentLevelResponse';
import {
    SegmentLevelResponseFromJSON,
    SegmentLevelResponseFromJSONTyped,
    SegmentLevelResponseToJSON,
    SegmentLevelResponseToJSONTyped,
} from './SegmentLevelResponse';

/**
 * Esquema para listado de segmentos de nivel
 * @export
 * @interface SegmentLevelListResponse
 */
export interface SegmentLevelListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SegmentLevelListResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SegmentLevelListResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<SegmentLevelResponse>}
     * @memberof SegmentLevelListResponse
     */
    data?: Array<SegmentLevelResponse>;
    /**
     * 
     * @type {number}
     * @memberof SegmentLevelListResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the SegmentLevelListResponse interface.
 */
export function instanceOfSegmentLevelListResponse(value: object): value is SegmentLevelListResponse {
    return true;
}

export function SegmentLevelListResponseFromJSON(json: any): SegmentLevelListResponse {
    return SegmentLevelListResponseFromJSONTyped(json, false);
}

export function SegmentLevelListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentLevelListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SegmentLevelResponseFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function SegmentLevelListResponseToJSON(json: any): SegmentLevelListResponse {
    return SegmentLevelListResponseToJSONTyped(json, false);
}

export function SegmentLevelListResponseToJSONTyped(value?: SegmentLevelListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SegmentLevelResponseToJSON)),
        'total': value['total'],
    };
}

