/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta de eliminación de segmento
 * @export
 * @interface SegmentLevelDeleteResponse
 */
export interface SegmentLevelDeleteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SegmentLevelDeleteResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SegmentLevelDeleteResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the SegmentLevelDeleteResponse interface.
 */
export function instanceOfSegmentLevelDeleteResponse(value: object): value is SegmentLevelDeleteResponse {
    return true;
}

export function SegmentLevelDeleteResponseFromJSON(json: any): SegmentLevelDeleteResponse {
    return SegmentLevelDeleteResponseFromJSONTyped(json, false);
}

export function SegmentLevelDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentLevelDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function SegmentLevelDeleteResponseToJSON(json: any): SegmentLevelDeleteResponse {
    return SegmentLevelDeleteResponseToJSONTyped(json, false);
}

export function SegmentLevelDeleteResponseToJSONTyped(value?: SegmentLevelDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

