/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para crear un nuevo segmento de nivel
 * @export
 * @interface SegmentLevelCreate
 */
export interface SegmentLevelCreate {
    /**
     * 
     * @type {object}
     * @memberof SegmentLevelCreate
     */
    _configuration?: object | null;
    /**
     * 
     * @type {number}
     * @memberof SegmentLevelCreate
     */
    level_id?: number | null;
}

/**
 * Check if a given object implements the SegmentLevelCreate interface.
 */
export function instanceOfSegmentLevelCreate(value: object): value is SegmentLevelCreate {
    return true;
}

export function SegmentLevelCreateFromJSON(json: any): SegmentLevelCreate {
    return SegmentLevelCreateFromJSONTyped(json, false);
}

export function SegmentLevelCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentLevelCreate {
    if (json == null) {
        return json;
    }
    return {
        
        '_configuration': json['configuration'] == null ? undefined : json['configuration'],
        'level_id': json['level_id'] == null ? undefined : json['level_id'],
    };
}

export function SegmentLevelCreateToJSON(json: any): SegmentLevelCreate {
    return SegmentLevelCreateToJSONTyped(json, false);
}

export function SegmentLevelCreateToJSONTyped(value?: SegmentLevelCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configuration': value['_configuration'],
        'level_id': value['level_id'],
    };
}

