/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para la respuesta de un segmento de nivel
 * @export
 * @interface SegmentLevelResponse
 */
export interface SegmentLevelResponse {
    /**
     * 
     * @type {object}
     * @memberof SegmentLevelResponse
     */
    _configuration?: object | null;
    /**
     * 
     * @type {Date}
     * @memberof SegmentLevelResponse
     */
    created_at: Date;
    /**
     * 
     * @type {number}
     * @memberof SegmentLevelResponse
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof SegmentLevelResponse
     */
    is_deleted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SegmentLevelResponse
     */
    level_number_id: number;
    /**
     * 
     * @type {Date}
     * @memberof SegmentLevelResponse
     */
    updated_at?: Date | null;
}

/**
 * Check if a given object implements the SegmentLevelResponse interface.
 */
export function instanceOfSegmentLevelResponse(value: object): value is SegmentLevelResponse {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('level_number_id' in value) || value['level_number_id'] === undefined) return false;
    return true;
}

export function SegmentLevelResponseFromJSON(json: any): SegmentLevelResponse {
    return SegmentLevelResponseFromJSONTyped(json, false);
}

export function SegmentLevelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentLevelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '_configuration': json['configuration'] == null ? undefined : json['configuration'],
        'created_at': (new Date(json['created_at'])),
        'id': json['id'],
        'is_deleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
        'level_number_id': json['level_number_id'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function SegmentLevelResponseToJSON(json: any): SegmentLevelResponse {
    return SegmentLevelResponseToJSONTyped(json, false);
}

export function SegmentLevelResponseToJSONTyped(value?: SegmentLevelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configuration': value['_configuration'],
        'created_at': value['created_at'].toISOString(),
        'id': value['id'],
        'is_deleted': value['is_deleted'],
        'level_number_id': value['level_number_id'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

