/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para actualizar un segmento de nivel
 * @export
 * @interface SegmentLevelUpdate
 */
export interface SegmentLevelUpdate {
    /**
     * 
     * @type {object}
     * @memberof SegmentLevelUpdate
     */
    _configuration?: object | null;
}

/**
 * Check if a given object implements the SegmentLevelUpdate interface.
 */
export function instanceOfSegmentLevelUpdate(value: object): value is SegmentLevelUpdate {
    return true;
}

export function SegmentLevelUpdateFromJSON(json: any): SegmentLevelUpdate {
    return SegmentLevelUpdateFromJSONTyped(json, false);
}

export function SegmentLevelUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentLevelUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        '_configuration': json['configuration'] == null ? undefined : json['configuration'],
    };
}

export function SegmentLevelUpdateToJSON(json: any): SegmentLevelUpdate {
    return SegmentLevelUpdateToJSONTyped(json, false);
}

export function SegmentLevelUpdateToJSONTyped(value?: SegmentLevelUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configuration': value['_configuration'],
    };
}

