/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SegmentLevelResponse } from './SegmentLevelResponse';
import {
    SegmentLevelResponseFromJSON,
    SegmentLevelResponseFromJSONTyped,
    SegmentLevelResponseToJSON,
    SegmentLevelResponseToJSONTyped,
} from './SegmentLevelResponse';

/**
 * Esquema para respuesta de actualización de segmento
 * @export
 * @interface SegmentLevelUpdateResponse
 */
export interface SegmentLevelUpdateResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SegmentLevelUpdateResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SegmentLevelUpdateResponse
     */
    message?: string;
    /**
     * 
     * @type {SegmentLevelResponse}
     * @memberof SegmentLevelUpdateResponse
     */
    data: SegmentLevelResponse;
}

/**
 * Check if a given object implements the SegmentLevelUpdateResponse interface.
 */
export function instanceOfSegmentLevelUpdateResponse(value: object): value is SegmentLevelUpdateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SegmentLevelUpdateResponseFromJSON(json: any): SegmentLevelUpdateResponse {
    return SegmentLevelUpdateResponseFromJSONTyped(json, false);
}

export function SegmentLevelUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentLevelUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': SegmentLevelResponseFromJSON(json['data']),
    };
}

export function SegmentLevelUpdateResponseToJSON(json: any): SegmentLevelUpdateResponse {
    return SegmentLevelUpdateResponseToJSONTyped(json, false);
}

export function SegmentLevelUpdateResponseToJSONTyped(value?: SegmentLevelUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': SegmentLevelResponseToJSON(value['data']),
    };
}

