/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SegmentLevelResponse } from './SegmentLevelResponse';
import {
    SegmentLevelResponseFromJSON,
    SegmentLevelResponseFromJSONTyped,
    SegmentLevelResponseToJSON,
    SegmentLevelResponseToJSONTyped,
} from './SegmentLevelResponse';

/**
 * Esquema para respuesta de creación de segmento
 * @export
 * @interface SegmentLevelCreateResponse
 */
export interface SegmentLevelCreateResponse {
    /**
     * 
     * @type {SegmentLevelResponse}
     * @memberof SegmentLevelCreateResponse
     */
    data: SegmentLevelResponse;
    /**
     * 
     * @type {string}
     * @memberof SegmentLevelCreateResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SegmentLevelCreateResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the SegmentLevelCreateResponse interface.
 */
export function instanceOfSegmentLevelCreateResponse(value: object): value is SegmentLevelCreateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SegmentLevelCreateResponseFromJSON(json: any): SegmentLevelCreateResponse {
    return SegmentLevelCreateResponseFromJSONTyped(json, false);
}

export function SegmentLevelCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentLevelCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SegmentLevelResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function SegmentLevelCreateResponseToJSON(json: any): SegmentLevelCreateResponse {
    return SegmentLevelCreateResponseToJSONTyped(json, false);
}

export function SegmentLevelCreateResponseToJSONTyped(value?: SegmentLevelCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SegmentLevelResponseToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

