/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameInstanceDetailResponse } from './GameInstanceDetailResponse';
import {
    GameInstanceDetailResponseFromJSON,
    GameInstanceDetailResponseFromJSONTyped,
    GameInstanceDetailResponseToJSON,
    GameInstanceDetailResponseToJSONTyped,
} from './GameInstanceDetailResponse';

/**
 * Esquema para respuesta de una sola instancia
 * @export
 * @interface SingleGameInstanceResponse
 */
export interface SingleGameInstanceResponse {
    /**
     * 
     * @type {GameInstanceDetailResponse}
     * @memberof SingleGameInstanceResponse
     */
    data?: GameInstanceDetailResponse | null;
    /**
     * 
     * @type {string}
     * @memberof SingleGameInstanceResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SingleGameInstanceResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the SingleGameInstanceResponse interface.
 */
export function instanceOfSingleGameInstanceResponse(value: object): value is SingleGameInstanceResponse {
    return true;
}

export function SingleGameInstanceResponseFromJSON(json: any): SingleGameInstanceResponse {
    return SingleGameInstanceResponseFromJSONTyped(json, false);
}

export function SingleGameInstanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleGameInstanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : GameInstanceDetailResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function SingleGameInstanceResponseToJSON(json: any): SingleGameInstanceResponse {
    return SingleGameInstanceResponseToJSONTyped(json, false);
}

export function SingleGameInstanceResponseToJSONTyped(value?: SingleGameInstanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GameInstanceDetailResponseToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

