/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameDetailResponse } from './GameDetailResponse';
import {
    GameDetailResponseFromJSON,
    GameDetailResponseFromJSONTyped,
    GameDetailResponseToJSON,
    GameDetailResponseToJSONTyped,
} from './GameDetailResponse';

/**
 * Esquema para respuesta de un solo juego
 * @export
 * @interface SingleGameResponse
 */
export interface SingleGameResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SingleGameResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SingleGameResponse
     */
    message?: string;
    /**
     * 
     * @type {GameDetailResponse}
     * @memberof SingleGameResponse
     */
    data?: GameDetailResponse | null;
}

/**
 * Check if a given object implements the SingleGameResponse interface.
 */
export function instanceOfSingleGameResponse(value: object): value is SingleGameResponse {
    return true;
}

export function SingleGameResponseFromJSON(json: any): SingleGameResponse {
    return SingleGameResponseFromJSONTyped(json, false);
}

export function SingleGameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleGameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : GameDetailResponseFromJSON(json['data']),
    };
}

export function SingleGameResponseToJSON(json: any): SingleGameResponse {
    return SingleGameResponseToJSONTyped(json, false);
}

export function SingleGameResponseToJSONTyped(value?: SingleGameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': GameDetailResponseToJSON(value['data']),
    };
}

