/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LevelDetailResponse } from './LevelDetailResponse';
import {
    LevelDetailResponseFromJSON,
    LevelDetailResponseFromJSONTyped,
    LevelDetailResponseToJSON,
    LevelDetailResponseToJSONTyped,
} from './LevelDetailResponse';

/**
 * Esquema para respuesta de un solo nivel
 * @export
 * @interface SingleLevelResponse
 */
export interface SingleLevelResponse {
    /**
     * 
     * @type {LevelDetailResponse}
     * @memberof SingleLevelResponse
     */
    data?: LevelDetailResponse | null;
    /**
     * 
     * @type {string}
     * @memberof SingleLevelResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SingleLevelResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the SingleLevelResponse interface.
 */
export function instanceOfSingleLevelResponse(value: object): value is SingleLevelResponse {
    return true;
}

export function SingleLevelResponseFromJSON(json: any): SingleLevelResponse {
    return SingleLevelResponseFromJSONTyped(json, false);
}

export function SingleLevelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleLevelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : LevelDetailResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function SingleLevelResponseToJSON(json: any): SingleLevelResponse {
    return SingleLevelResponseToJSONTyped(json, false);
}

export function SingleLevelResponseToJSONTyped(value?: SingleLevelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': LevelDetailResponseToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

