/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * Respuesta para un solo usuario
 * @export
 * @interface SingleUserResponse
 */
export interface SingleUserResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SingleUserResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SingleUserResponse
     */
    message?: string;
    /**
     * 
     * @type {UserResponse}
     * @memberof SingleUserResponse
     */
    data?: UserResponse | null;
    /**
     * 
     * @type {any}
     * @memberof SingleUserResponse
     */
    error?: any | null;
}

/**
 * Check if a given object implements the SingleUserResponse interface.
 */
export function instanceOfSingleUserResponse(value: object): value is SingleUserResponse {
    return true;
}

export function SingleUserResponseFromJSON(json: any): SingleUserResponse {
    return SingleUserResponseFromJSONTyped(json, false);
}

export function SingleUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : UserResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function SingleUserResponseToJSON(json: any): SingleUserResponse {
    return SingleUserResponseToJSONTyped(json, false);
}

export function SingleUserResponseToJSONTyped(value?: SingleUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': UserResponseToJSON(value['data']),
        'error': value['error'],
    };
}

