/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para crear un nuevo estudiante
 * @export
 * @interface StudentCreate
 */
export interface StudentCreate {
    /**
     * 
     * @type {string}
     * @memberof StudentCreate
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof StudentCreate
     */
    is_active?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof StudentCreate
     */
    lastname: string;
    /**
     * 
     * @type {string}
     * @memberof StudentCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StudentCreate
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof StudentCreate
     */
    username: string;
}

/**
 * Check if a given object implements the StudentCreate interface.
 */
export function instanceOfStudentCreate(value: object): value is StudentCreate {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('lastname' in value) || value['lastname'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function StudentCreateFromJSON(json: any): StudentCreate {
    return StudentCreateFromJSONTyped(json, false);
}

export function StudentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
        'lastname': json['lastname'],
        'name': json['name'],
        'password': json['password'],
        'username': json['username'],
    };
}

export function StudentCreateToJSON(json: any): StudentCreate {
    return StudentCreateToJSONTyped(json, false);
}

export function StudentCreateToJSONTyped(value?: StudentCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'is_active': value['is_active'],
        'lastname': value['lastname'],
        'name': value['name'],
        'password': value['password'],
        'username': value['username'],
    };
}

