/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para actualizar la información del estudiante
 * @export
 * @interface StudentUpdate
 */
export interface StudentUpdate {
    /**
     * 
     * @type {string}
     * @memberof StudentUpdate
     */
    email?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StudentUpdate
     */
    is_active?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof StudentUpdate
     */
    lastname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StudentUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StudentUpdate
     */
    username?: string | null;
}

/**
 * Check if a given object implements the StudentUpdate interface.
 */
export function instanceOfStudentUpdate(value: object): value is StudentUpdate {
    return true;
}

export function StudentUpdateFromJSON(json: any): StudentUpdate {
    return StudentUpdateFromJSONTyped(json, false);
}

export function StudentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'name': json['name'] == null ? undefined : json['name'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function StudentUpdateToJSON(json: any): StudentUpdate {
    return StudentUpdateToJSONTyped(json, false);
}

export function StudentUpdateToJSONTyped(value?: StudentUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'is_active': value['is_active'],
        'lastname': value['lastname'],
        'name': value['name'],
        'username': value['username'],
    };
}

