/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para la respuesta individual del estudiante
 * @export
 * @interface StudentResponse
 */
export interface StudentResponse {
    /**
     * 
     * @type {Date}
     * @memberof StudentResponse
     */
    created_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof StudentResponse
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof StudentResponse
     */
    is_active: boolean;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    lastname: string;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof StudentResponse
     */
    updated_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    username: string;
}

/**
 * Check if a given object implements the StudentResponse interface.
 */
export function instanceOfStudentResponse(value: object): value is StudentResponse {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('is_active' in value) || value['is_active'] === undefined) return false;
    if (!('lastname' in value) || value['lastname'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function StudentResponseFromJSON(json: any): StudentResponse {
    return StudentResponseFromJSONTyped(json, false);
}

export function StudentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'email': json['email'],
        'id': json['id'],
        'is_active': json['is_active'],
        'lastname': json['lastname'],
        'name': json['name'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'username': json['username'],
    };
}

export function StudentResponseToJSON(json: any): StudentResponse {
    return StudentResponseToJSONTyped(json, false);
}

export function StudentResponseToJSONTyped(value?: StudentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
        'email': value['email'],
        'id': value['id'],
        'is_active': value['is_active'],
        'lastname': value['lastname'],
        'name': value['name'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
        'username': value['username'],
    };
}

