/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para la respuesta de reportes del estudiante
 * @export
 * @interface StudentReportsResponse
 */
export interface StudentReportsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StudentReportsResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StudentReportsResponse
     */
    message?: string;
    /**
     * 
     * @type {object}
     * @memberof StudentReportsResponse
     */
    data: object;
    /**
     * 
     * @type {}
     * @memberof StudentReportsResponse
     */
    error?:  | null;
}

/**
 * Check if a given object implements the StudentReportsResponse interface.
 */
export function instanceOfStudentReportsResponse(value: object): value is StudentReportsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function StudentReportsResponseFromJSON(json: any): StudentReportsResponse {
    return StudentReportsResponseFromJSONTyped(json, false);
}

export function StudentReportsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentReportsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'],
        'error': json['error'] == null ? undefined : FromJSON(json['error']),
    };
}

export function StudentReportsResponseToJSON(json: any): StudentReportsResponse {
    return StudentReportsResponseToJSONTyped(json, false);
}

export function StudentReportsResponseToJSONTyped(value?: StudentReportsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'],
        'error': ToJSON(value['error']),
    };
}

