/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudentResponse } from './StudentResponse';
import {
    StudentResponseFromJSON,
    StudentResponseFromJSONTyped,
    StudentResponseToJSON,
    StudentResponseToJSONTyped,
} from './StudentResponse';

/**
 * Esquema para la respuesta de listado de estudiantes
 * @export
 * @interface StudentListResponse
 */
export interface StudentListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StudentListResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StudentListResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<StudentResponse>}
     * @memberof StudentListResponse
     */
    data: Array<StudentResponse>;
    /**
     * 
     * @type {}
     * @memberof StudentListResponse
     */
    error?:  | null;
}

/**
 * Check if a given object implements the StudentListResponse interface.
 */
export function instanceOfStudentListResponse(value: object): value is StudentListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function StudentListResponseFromJSON(json: any): StudentListResponse {
    return StudentListResponseFromJSONTyped(json, false);
}

export function StudentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': ((json['data'] as Array<any>).map(StudentResponseFromJSON)),
        'error': json['error'] == null ? undefined : FromJSON(json['error']),
    };
}

export function StudentListResponseToJSON(json: any): StudentListResponse {
    return StudentListResponseToJSONTyped(json, false);
}

export function StudentListResponseToJSONTyped(value?: StudentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': ((value['data'] as Array<any>).map(StudentResponseToJSON)),
        'error': ToJSON(value['error']),
    };
}

