/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para la respuesta de progreso del estudiante
 * @export
 * @interface StudentProgressResponse
 */
export interface StudentProgressResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StudentProgressResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StudentProgressResponse
     */
    message?: string;
    /**
     * 
     * @type {object}
     * @memberof StudentProgressResponse
     */
    data: object;
    /**
     * 
     * @type {}
     * @memberof StudentProgressResponse
     */
    error?: any | null;
}

/**
 * Check if a given object implements the StudentProgressResponse interface.
 */
export function instanceOfStudentProgressResponse(value: object): value is StudentProgressResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function StudentProgressResponseFromJSON(json: any): StudentProgressResponse {
    return StudentProgressResponseFromJSONTyped(json, false);
}

export function StudentProgressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentProgressResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function StudentProgressResponseToJSON(json: any): StudentProgressResponse {
    return StudentProgressResponseToJSONTyped(json, false);
}

export function StudentProgressResponseToJSONTyped(value?: StudentProgressResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'],
        'error': value['error'],
    };
}

