/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncSessionCreate
 */
export interface SyncSessionCreate {
    /**
     * 
     * @type {number}
     * @memberof SyncSessionCreate
     */
    instanceId: number;
    /**
     * 
     * @type {boolean}
     * @memberof SyncSessionCreate
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the SyncSessionCreate interface.
 */
export function instanceOfSyncSessionCreate(value: object): value is SyncSessionCreate {
    if (!('instanceId' in value) || value['instanceId'] === undefined) return false;
    return true;
}

export function SyncSessionCreateFromJSON(json: any): SyncSessionCreate {
    return SyncSessionCreateFromJSONTyped(json, false);
}

export function SyncSessionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncSessionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'instanceId': json['instance_id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function SyncSessionCreateToJSON(json: any): SyncSessionCreate {
    return SyncSessionCreateToJSONTyped(json, false);
}

export function SyncSessionCreateToJSONTyped(value?: SyncSessionCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instance_id': value['instanceId'],
        'is_active': value['isActive'],
    };
}

