/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response schema for LMS sync operation.
 * @export
 * @interface SyncResultResponse
 */
export interface SyncResultResponse {
    /**
     * 
     * @type {string}
     * @memberof SyncResultResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncResultResponse
     */
    message: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof SyncResultResponse
     */
    recordsSynced: { [key: string]: number; };
    /**
     * 
     * @type {Date}
     * @memberof SyncResultResponse
     */
    syncTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof SyncResultResponse
     */
    nextSyncScheduled?: Date | null;
}

/**
 * Check if a given object implements the SyncResultResponse interface.
 */
export function instanceOfSyncResultResponse(value: object): value is SyncResultResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('recordsSynced' in value) || value['recordsSynced'] === undefined) return false;
    if (!('syncTime' in value) || value['syncTime'] === undefined) return false;
    return true;
}

export function SyncResultResponseFromJSON(json: any): SyncResultResponse {
    return SyncResultResponseFromJSONTyped(json, false);
}

export function SyncResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'],
        'recordsSynced': json['records_synced'],
        'syncTime': (new Date(json['sync_time'])),
        'nextSyncScheduled': json['next_sync_scheduled'] == null ? undefined : (new Date(json['next_sync_scheduled'])),
    };
}

export function SyncResultResponseToJSON(json: any): SyncResultResponse {
    return SyncResultResponseToJSONTyped(json, false);
}

export function SyncResultResponseToJSONTyped(value?: SyncResultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'records_synced': value['recordsSynced'],
        'sync_time': value['syncTime'].toISOString(),
        'next_sync_scheduled': value['nextSyncScheduled'] == null ? value['nextSyncScheduled'] : value['nextSyncScheduled'].toISOString(),
    };
}

