/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncSessionSchema
 */
export interface SyncSessionSchema {
    /**
     * 
     * @type {Date}
     * @memberof SyncSessionSchema
     */
    end_time?: Date | null;
    /**
     * Session ID
     * @type {number}
     * @memberof SyncSessionSchema
     */
    id: number;
    /**
     * ID of the game instance
     * @type {number}
     * @memberof SyncSessionSchema
     */
    instance_id: number;
    /**
     * Whether the session is active
     * @type {boolean}
     * @memberof SyncSessionSchema
     */
    is_active?: boolean;
    /**
     * Session start timestamp
     * @type {Date}
     * @memberof SyncSessionSchema
     */
    start_time: Date;
}

/**
 * Check if a given object implements the SyncSessionSchema interface.
 */
export function instanceOfSyncSessionSchema(value: object): value is SyncSessionSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('instance_id' in value) || value['instance_id'] === undefined) return false;
    if (!('start_time' in value) || value['start_time'] === undefined) return false;
    return true;
}

export function SyncSessionSchemaFromJSON(json: any): SyncSessionSchema {
    return SyncSessionSchemaFromJSONTyped(json, false);
}

export function SyncSessionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncSessionSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'end_time': json['end_time'] == null ? undefined : (new Date(json['end_time'])),
        'id': json['id'],
        'instance_id': json['instance_id'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
        'start_time': (new Date(json['start_time'])),
    };
}

export function SyncSessionSchemaToJSON(json: any): SyncSessionSchema {
    return SyncSessionSchemaToJSONTyped(json, false);
}

export function SyncSessionSchemaToJSONTyped(value?: SyncSessionSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_time': value['end_time'] == null ? value['end_time'] : value['end_time'].toISOString(),
        'id': value['id'],
        'instance_id': value['instance_id'],
        'is_active': value['is_active'],
        'start_time': value['start_time'].toISOString(),
    };
}

