/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncEventSchema
 */
export interface SyncEventSchema {
    /**
     * 
     * @type {number}
     * @memberof SyncEventSchema
     */
    syncSessionId: number;
    /**
     * 
     * @type {string}
     * @memberof SyncEventSchema
     */
    eventType: string;
    /**
     * 
     * @type {object}
     * @memberof SyncEventSchema
     */
    payload?: object | null;
    /**
     * 
     * @type {number}
     * @memberof SyncEventSchema
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof SyncEventSchema
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof SyncEventSchema
     */
    status?: string | null;
}

/**
 * Check if a given object implements the SyncEventSchema interface.
 */
export function instanceOfSyncEventSchema(value: object): value is SyncEventSchema {
    if (!('syncSessionId' in value) || value['syncSessionId'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function SyncEventSchemaFromJSON(json: any): SyncEventSchema {
    return SyncEventSchemaFromJSONTyped(json, false);
}

export function SyncEventSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncEventSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'syncSessionId': json['sync_session_id'],
        'eventType': json['event_type'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'id': json['id'],
        'timestamp': (new Date(json['timestamp'])),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function SyncEventSchemaToJSON(json: any): SyncEventSchema {
    return SyncEventSchemaToJSONTyped(json, false);
}

export function SyncEventSchemaToJSONTyped(value?: SyncEventSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sync_session_id': value['syncSessionId'],
        'event_type': value['eventType'],
        'payload': value['payload'],
        'id': value['id'],
        'timestamp': value['timestamp'].toISOString(),
        'status': value['status'],
    };
}

