/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncEventCreate
 */
export interface SyncEventCreate {
    /**
     * Type of the event
     * @type {string}
     * @memberof SyncEventCreate
     */
    event_type: string;
    /**
     * 
     * @type {object}
     * @memberof SyncEventCreate
     */
    payload?: object | null;
    /**
     * ID of the sync session
     * @type {number}
     * @memberof SyncEventCreate
     */
    sync_session_id: number;
}

/**
 * Check if a given object implements the SyncEventCreate interface.
 */
export function instanceOfSyncEventCreate(value: object): value is SyncEventCreate {
    if (!('event_type' in value) || value['event_type'] === undefined) return false;
    if (!('sync_session_id' in value) || value['sync_session_id'] === undefined) return false;
    return true;
}

export function SyncEventCreateFromJSON(json: any): SyncEventCreate {
    return SyncEventCreateFromJSONTyped(json, false);
}

export function SyncEventCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncEventCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'event_type': json['event_type'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'sync_session_id': json['sync_session_id'],
    };
}

export function SyncEventCreateToJSON(json: any): SyncEventCreate {
    return SyncEventCreateToJSONTyped(json, false);
}

export function SyncEventCreateToJSONTyped(value?: SyncEventCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_type': value['event_type'],
        'payload': value['payload'],
        'sync_session_id': value['sync_session_id'],
    };
}

