/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncSessionSchema
 */
export interface SyncSessionSchema {
    /**
     * 
     * @type {number}
     * @memberof SyncSessionSchema
     */
    instanceId: number;
    /**
     * 
     * @type {boolean}
     * @memberof SyncSessionSchema
     */
    isActive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SyncSessionSchema
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof SyncSessionSchema
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SyncSessionSchema
     */
    endedAt?: Date | null;
}

/**
 * Check if a given object implements the SyncSessionSchema interface.
 */
export function instanceOfSyncSessionSchema(value: object): value is SyncSessionSchema {
    if (!('instanceId' in value) || value['instanceId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    return true;
}

export function SyncSessionSchemaFromJSON(json: any): SyncSessionSchema {
    return SyncSessionSchemaFromJSONTyped(json, false);
}

export function SyncSessionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncSessionSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'instanceId': json['instance_id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'id': json['id'],
        'startedAt': (new Date(json['started_at'])),
        'endedAt': json['ended_at'] == null ? undefined : (new Date(json['ended_at'])),
    };
}

export function SyncSessionSchemaToJSON(json: any): SyncSessionSchema {
    return SyncSessionSchemaToJSONTyped(json, false);
}

export function SyncSessionSchemaToJSONTyped(value?: SyncSessionSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instance_id': value['instanceId'],
        'is_active': value['isActive'],
        'id': value['id'],
        'started_at': value['startedAt'].toISOString(),
        'ended_at': value['endedAt'] == null ? value['endedAt'] : value['endedAt'].toISOString(),
    };
}

