/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para actualización de configuraciones de profesor
 * @export
 * @interface TeacherSettingsUpdate
 */
export interface TeacherSettingsUpdate {
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsUpdate
     */
    theme?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TeacherSettingsUpdate
     */
    notificationsEnabled?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsUpdate
     */
    notificationFrequency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsUpdate
     */
    interfaceLanguage?: string | null;
}

/**
 * Check if a given object implements the TeacherSettingsUpdate interface.
 */
export function instanceOfTeacherSettingsUpdate(value: object): value is TeacherSettingsUpdate {
    return true;
}

export function TeacherSettingsUpdateFromJSON(json: any): TeacherSettingsUpdate {
    return TeacherSettingsUpdateFromJSONTyped(json, false);
}

export function TeacherSettingsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherSettingsUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'theme': json['theme'] == null ? undefined : json['theme'],
        'notificationsEnabled': json['notifications_enabled'] == null ? undefined : json['notifications_enabled'],
        'notificationFrequency': json['notification_frequency'] == null ? undefined : json['notification_frequency'],
        'interfaceLanguage': json['interface_language'] == null ? undefined : json['interface_language'],
    };
}

export function TeacherSettingsUpdateToJSON(json: any): TeacherSettingsUpdate {
    return TeacherSettingsUpdateToJSONTyped(json, false);
}

export function TeacherSettingsUpdateToJSONTyped(value?: TeacherSettingsUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'theme': value['theme'],
        'notifications_enabled': value['notificationsEnabled'],
        'notification_frequency': value['notificationFrequency'],
        'interface_language': value['interfaceLanguage'],
    };
}

