/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta de configuraciones de profesor
 * @export
 * @interface TeacherSettingsResponse
 */
export interface TeacherSettingsResponse {
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsResponse
     */
    theme?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TeacherSettingsResponse
     */
    notificationsEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsResponse
     */
    notificationFrequency?: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsResponse
     */
    interfaceLanguage?: string;
}

/**
 * Check if a given object implements the TeacherSettingsResponse interface.
 */
export function instanceOfTeacherSettingsResponse(value: object): value is TeacherSettingsResponse {
    return true;
}

export function TeacherSettingsResponseFromJSON(json: any): TeacherSettingsResponse {
    return TeacherSettingsResponseFromJSONTyped(json, false);
}

export function TeacherSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherSettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'theme': json['theme'] == null ? undefined : json['theme'],
        'notificationsEnabled': json['notifications_enabled'] == null ? undefined : json['notifications_enabled'],
        'notificationFrequency': json['notification_frequency'] == null ? undefined : json['notification_frequency'],
        'interfaceLanguage': json['interface_language'] == null ? undefined : json['interface_language'],
    };
}

export function TeacherSettingsResponseToJSON(json: any): TeacherSettingsResponse {
    return TeacherSettingsResponseToJSONTyped(json, false);
}

export function TeacherSettingsResponseToJSONTyped(value?: TeacherSettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'theme': value['theme'],
        'notifications_enabled': value['notificationsEnabled'],
        'notification_frequency': value['notificationFrequency'],
        'interface_language': value['interfaceLanguage'],
    };
}

