/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta del perfil de profesor
 * @export
 * @interface TeacherProfileResponse
 */
export interface TeacherProfileResponse {
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileResponse
     */
    avatar_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileResponse
     */
    contact_phone?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TeacherProfileResponse
     */
    created_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileResponse
     */
    department: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileResponse
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof TeacherProfileResponse
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof TeacherProfileResponse
     */
    is_active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileResponse
     */
    lastname: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof TeacherProfileResponse
     */
    updated_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileResponse
     */
    username: string;
}

/**
 * Check if a given object implements the TeacherProfileResponse interface.
 */
export function instanceOfTeacherProfileResponse(value: object): value is TeacherProfileResponse {
    if (!('department' in value) || value['department'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lastname' in value) || value['lastname'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function TeacherProfileResponseFromJSON(json: any): TeacherProfileResponse {
    return TeacherProfileResponseFromJSONTyped(json, false);
}

export function TeacherProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherProfileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar_url': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'contact_phone': json['contact_phone'] == null ? undefined : json['contact_phone'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'department': json['department'],
        'email': json['email'],
        'id': json['id'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
        'lastname': json['lastname'],
        'name': json['name'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'username': json['username'],
    };
}

export function TeacherProfileResponseToJSON(json: any): TeacherProfileResponse {
    return TeacherProfileResponseToJSONTyped(json, false);
}

export function TeacherProfileResponseToJSONTyped(value?: TeacherProfileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar_url': value['avatar_url'],
        'contact_phone': value['contact_phone'],
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
        'department': value['department'],
        'email': value['email'],
        'id': value['id'],
        'is_active': value['is_active'],
        'lastname': value['lastname'],
        'name': value['name'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
        'username': value['username'],
    };
}

