/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeacherProfileResponse } from './TeacherProfileResponse';
import {
    TeacherProfileResponseFromJSON,
    TeacherProfileResponseFromJSONTyped,
    TeacherProfileResponseToJSON,
    TeacherProfileResponseToJSONTyped,
} from './TeacherProfileResponse';

/**
 * Respuesta para actualizaciones de profesor
 * @export
 * @interface TeacherUpdateResponseSchema
 */
export interface TeacherUpdateResponseSchema {
    /**
     * 
     * @type {boolean}
     * @memberof TeacherUpdateResponseSchema
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TeacherUpdateResponseSchema
     */
    message?: string;
    /**
     * 
     * @type {TeacherProfileResponse}
     * @memberof TeacherUpdateResponseSchema
     */
    data: TeacherProfileResponse;
    /**
     * 
     * @type {}
     * @memberof TeacherUpdateResponseSchema
     */
    error?: any | null;
}

/**
 * Check if a given object implements the TeacherUpdateResponseSchema interface.
 */
export function instanceOfTeacherUpdateResponseSchema(value: object): value is TeacherUpdateResponseSchema {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TeacherUpdateResponseSchemaFromJSON(json: any): TeacherUpdateResponseSchema {
    return TeacherUpdateResponseSchemaFromJSONTyped(json, false);
}

export function TeacherUpdateResponseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherUpdateResponseSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': TeacherProfileResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function TeacherUpdateResponseSchemaToJSON(json: any): TeacherUpdateResponseSchema {
    return TeacherUpdateResponseSchemaToJSONTyped(json, false);
}

export function TeacherUpdateResponseSchemaToJSONTyped(value?: TeacherUpdateResponseSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': TeacherProfileResponseToJSON(value['data']),
        'error': value['error'],
    };
}

