/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para actualización del perfil de profesor
 * @export
 * @interface TeacherProfileUpdate
 */
export interface TeacherProfileUpdate {
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileUpdate
     */
    lastname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileUpdate
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileUpdate
     */
    department?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileUpdate
     */
    contactPhone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherProfileUpdate
     */
    avatarUrl?: string | null;
}

/**
 * Check if a given object implements the TeacherProfileUpdate interface.
 */
export function instanceOfTeacherProfileUpdate(value: object): value is TeacherProfileUpdate {
    return true;
}

export function TeacherProfileUpdateFromJSON(json: any): TeacherProfileUpdate {
    return TeacherProfileUpdateFromJSONTyped(json, false);
}

export function TeacherProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherProfileUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'email': json['email'] == null ? undefined : json['email'],
        'department': json['department'] == null ? undefined : json['department'],
        'contactPhone': json['contact_phone'] == null ? undefined : json['contact_phone'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
    };
}

export function TeacherProfileUpdateToJSON(json: any): TeacherProfileUpdate {
    return TeacherProfileUpdateToJSONTyped(json, false);
}

export function TeacherProfileUpdateToJSONTyped(value?: TeacherProfileUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'lastname': value['lastname'],
        'email': value['email'],
        'department': value['department'],
        'contact_phone': value['contactPhone'],
        'avatar_url': value['avatarUrl'],
    };
}

