/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para actualización de configuraciones de profesor
 * @export
 * @interface TeacherSettingsUpdate
 */
export interface TeacherSettingsUpdate {
    /**
     * 
     * @type {boolean}
     * @memberof TeacherSettingsUpdate
     */
    animations_enabled?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof TeacherSettingsUpdate
     */
    auto_logout?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsUpdate
     */
    color_theme?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsUpdate
     */
    date_format?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TeacherSettingsUpdate
     */
    email_notifications?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsUpdate
     */
    interface_language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsUpdate
     */
    notification_frequency?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TeacherSettingsUpdate
     */
    notifications_enabled?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof TeacherSettingsUpdate
     */
    remember_login?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof TeacherSettingsUpdate
     */
    session_duration_minutes?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsUpdate
     */
    theme?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeacherSettingsUpdate
     */
    timezone?: string | null;
}

/**
 * Check if a given object implements the TeacherSettingsUpdate interface.
 */
export function instanceOfTeacherSettingsUpdate(value: object): value is TeacherSettingsUpdate {
    return true;
}

export function TeacherSettingsUpdateFromJSON(json: any): TeacherSettingsUpdate {
    return TeacherSettingsUpdateFromJSONTyped(json, false);
}

export function TeacherSettingsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherSettingsUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'animations_enabled': json['animations_enabled'] == null ? undefined : json['animations_enabled'],
        'auto_logout': json['auto_logout'] == null ? undefined : json['auto_logout'],
        'color_theme': json['color_theme'] == null ? undefined : json['color_theme'],
        'date_format': json['date_format'] == null ? undefined : json['date_format'],
        'email_notifications': json['email_notifications'] == null ? undefined : json['email_notifications'],
        'interface_language': json['interface_language'] == null ? undefined : json['interface_language'],
        'notification_frequency': json['notification_frequency'] == null ? undefined : json['notification_frequency'],
        'notifications_enabled': json['notifications_enabled'] == null ? undefined : json['notifications_enabled'],
        'remember_login': json['remember_login'] == null ? undefined : json['remember_login'],
        'session_duration_minutes': json['session_duration_minutes'] == null ? undefined : json['session_duration_minutes'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function TeacherSettingsUpdateToJSON(json: any): TeacherSettingsUpdate {
    return TeacherSettingsUpdateToJSONTyped(json, false);
}

export function TeacherSettingsUpdateToJSONTyped(value?: TeacherSettingsUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'animations_enabled': value['animations_enabled'],
        'auto_logout': value['auto_logout'],
        'color_theme': value['color_theme'],
        'date_format': value['date_format'],
        'email_notifications': value['email_notifications'],
        'interface_language': value['interface_language'],
        'notification_frequency': value['notification_frequency'],
        'notifications_enabled': value['notifications_enabled'],
        'remember_login': value['remember_login'],
        'session_duration_minutes': value['session_duration_minutes'],
        'theme': value['theme'],
        'timezone': value['timezone'],
    };
}

