/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Esquema para respuesta de rol
 * @export
 * @interface UserRoleResponse
 */
export interface UserRoleResponse {
    /**
     * 
     * @type {number}
     * @memberof UserRoleResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserRoleResponse
     */
    role_name: string;
}

/**
 * Check if a given object implements the UserRoleResponse interface.
 */
export function instanceOfUserRoleResponse(value: object): value is UserRoleResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('role_name' in value) || value['role_name'] === undefined) return false;
    return true;
}

export function UserRoleResponseFromJSON(json: any): UserRoleResponse {
    return UserRoleResponseFromJSONTyped(json, false);
}

export function UserRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role_name': json['role_name'],
    };
}

export function UserRoleResponseToJSON(json: any): UserRoleResponse {
    return UserRoleResponseToJSONTyped(json, false);
}

export function UserRoleResponseToJSONTyped(value?: UserRoleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role_name': value['role_name'],
    };
}

