/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRoleResponse } from './UserRoleResponse';
import {
    UserRoleResponseFromJSON,
    UserRoleResponseFromJSONTyped,
    UserRoleResponseToJSON,
    UserRoleResponseToJSONTyped,
} from './UserRoleResponse';

/**
 * Esquema para respuesta de usuario
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {Date}
     * @memberof UserResponse
     */
    created_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponse
     */
    is_active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    lastname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    name: string;
    /**
     * 
     * @type {UserRoleResponse}
     * @memberof UserResponse
     */
    role?: UserRoleResponse | null;
    /**
     * 
     * @type {Date}
     * @memberof UserResponse
     */
    updated_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    username: string;
}

/**
 * Check if a given object implements the UserResponse interface.
 */
export function instanceOfUserResponse(value: object): value is UserResponse {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return UserResponseFromJSONTyped(json, false);
}

export function UserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'email': json['email'],
        'id': json['id'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'name': json['name'],
        'role': json['role'] == null ? undefined : UserRoleResponseFromJSON(json['role']),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'username': json['username'],
    };
}

export function UserResponseToJSON(json: any): UserResponse {
    return UserResponseToJSONTyped(json, false);
}

export function UserResponseToJSONTyped(value?: UserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
        'email': value['email'],
        'id': value['id'],
        'is_active': value['is_active'],
        'lastname': value['lastname'],
        'name': value['name'],
        'role': UserRoleResponseToJSON(value['role']),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
        'username': value['username'],
    };
}

