/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * Respuesta de autenticación exitosa
 * @export
 * @interface UserLoginResponse
 */
export interface UserLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    tokenType?: string;
    /**
     * 
     * @type {number}
     * @memberof UserLoginResponse
     */
    expiresIn: number;
    /**
     * 
     * @type {UserResponse}
     * @memberof UserLoginResponse
     */
    user: UserResponse;
}

/**
 * Check if a given object implements the UserLoginResponse interface.
 */
export function instanceOfUserLoginResponse(value: object): value is UserLoginResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function UserLoginResponseFromJSON(json: any): UserLoginResponse {
    return UserLoginResponseFromJSONTyped(json, false);
}

export function UserLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'expiresIn': json['expires_in'],
        'user': UserResponseFromJSON(json['user']),
    };
}

export function UserLoginResponseToJSON(json: any): UserLoginResponse {
    return UserLoginResponseToJSONTyped(json, false);
}

export function UserLoginResponseToJSONTyped(value?: UserLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
        'user': UserResponseToJSON(value['user']),
    };
}

