/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XAPIActivityDefinition } from './XAPIActivityDefinition';
import {
    XAPIActivityDefinitionFromJSON,
    XAPIActivityDefinitionFromJSONTyped,
    XAPIActivityDefinitionToJSON,
    XAPIActivityDefinitionToJSONTyped,
} from './XAPIActivityDefinition';

/**
 * xAPI Activity - The object of the action.
 * @export
 * @interface XAPIActivity
 */
export interface XAPIActivity {
    /**
     * IRI of the activity
     * @type {string}
     * @memberof XAPIActivity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof XAPIActivity
     */
    objectType?: string | null;
    /**
     * 
     * @type {XAPIActivityDefinition}
     * @memberof XAPIActivity
     */
    definition?: XAPIActivityDefinition | null;
}

/**
 * Check if a given object implements the XAPIActivity interface.
 */
export function instanceOfXAPIActivity(value: object): value is XAPIActivity {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function XAPIActivityFromJSON(json: any): XAPIActivity {
    return XAPIActivityFromJSONTyped(json, false);
}

export function XAPIActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'objectType': json['object_type'] == null ? undefined : json['object_type'],
        'definition': json['definition'] == null ? undefined : XAPIActivityDefinitionFromJSON(json['definition']),
    };
}

export function XAPIActivityToJSON(json: any): XAPIActivity {
    return XAPIActivityToJSONTyped(json, false);
}

export function XAPIActivityToJSONTyped(value?: XAPIActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object_type': value['objectType'],
        'definition': XAPIActivityDefinitionToJSON(value['definition']),
    };
}

