/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * xAPI Activity definition with type, name, description.
 * @export
 * @interface XAPIActivityDefinition
 */
export interface XAPIActivityDefinition {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof XAPIActivityDefinition
     */
    description?: { [key: string]: string; } | null;
    /**
     * 
     * @type {object}
     * @memberof XAPIActivityDefinition
     */
    extensions?: object | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof XAPIActivityDefinition
     */
    name?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof XAPIActivityDefinition
     */
    type?: string | null;
}

/**
 * Check if a given object implements the XAPIActivityDefinition interface.
 */
export function instanceOfXAPIActivityDefinition(value: object): value is XAPIActivityDefinition {
    return true;
}

export function XAPIActivityDefinitionFromJSON(json: any): XAPIActivityDefinition {
    return XAPIActivityDefinitionFromJSONTyped(json, false);
}

export function XAPIActivityDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIActivityDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'extensions': json['extensions'] == null ? undefined : json['extensions'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function XAPIActivityDefinitionToJSON(json: any): XAPIActivityDefinition {
    return XAPIActivityDefinitionToJSONTyped(json, false);
}

export function XAPIActivityDefinitionToJSONTyped(value?: XAPIActivityDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'extensions': value['extensions'],
        'name': value['name'],
        'type': value['type'],
    };
}

