/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XAPIScore } from './XAPIScore';
import {
    XAPIScoreFromJSON,
    XAPIScoreFromJSONTyped,
    XAPIScoreToJSON,
    XAPIScoreToJSONTyped,
} from './XAPIScore';

/**
 * xAPI Result - The result of the action (quantitative and qualitative).
 * @export
 * @interface XAPIResult
 */
export interface XAPIResult {
    /**
     * 
     * @type {XAPIScore}
     * @memberof XAPIResult
     */
    score?: XAPIScore | null;
    /**
     * 
     * @type {boolean}
     * @memberof XAPIResult
     */
    success?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof XAPIResult
     */
    completion?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof XAPIResult
     */
    response?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XAPIResult
     */
    duration?: string | null;
    /**
     * 
     * @type {object}
     * @memberof XAPIResult
     */
    extensions?: object | null;
}

/**
 * Check if a given object implements the XAPIResult interface.
 */
export function instanceOfXAPIResult(value: object): value is XAPIResult {
    return true;
}

export function XAPIResultFromJSON(json: any): XAPIResult {
    return XAPIResultFromJSONTyped(json, false);
}

export function XAPIResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIResult {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : XAPIScoreFromJSON(json['score']),
        'success': json['success'] == null ? undefined : json['success'],
        'completion': json['completion'] == null ? undefined : json['completion'],
        'response': json['response'] == null ? undefined : json['response'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'extensions': json['extensions'] == null ? undefined : json['extensions'],
    };
}

export function XAPIResultToJSON(json: any): XAPIResult {
    return XAPIResultToJSONTyped(json, false);
}

export function XAPIResultToJSONTyped(value?: XAPIResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': XAPIScoreToJSON(value['score']),
        'success': value['success'],
        'completion': value['completion'],
        'response': value['response'],
        'duration': value['duration'],
        'extensions': value['extensions'],
    };
}

