/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * xAPI Actor types.
 * @export
 */
export const XAPIActorType = {
    Agent: 'Agent',
    Group: 'Group'
} as const;
export type XAPIActorType = typeof XAPIActorType[keyof typeof XAPIActorType];


export function instanceOfXAPIActorType(value: any): boolean {
    for (const key in XAPIActorType) {
        if (Object.prototype.hasOwnProperty.call(XAPIActorType, key)) {
            if (XAPIActorType[key as keyof typeof XAPIActorType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function XAPIActorTypeFromJSON(json: any): XAPIActorType {
    return XAPIActorTypeFromJSONTyped(json, false);
}

export function XAPIActorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIActorType {
    return json as XAPIActorType;
}

export function XAPIActorTypeToJSON(value?: XAPIActorType | null): any {
    return value as any;
}

export function XAPIActorTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): XAPIActorType {
    return value as XAPIActorType;
}

