/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XAPIActor } from './XAPIActor';
import {
    XAPIActorFromJSON,
    XAPIActorFromJSONTyped,
    XAPIActorToJSON,
    XAPIActorToJSONTyped,
} from './XAPIActor';

/**
 * xAPI Context - Additional context information.
 * @export
 * @interface XAPIContextInput
 */
export interface XAPIContextInput {
    /**
     * 
     * @type {string}
     * @memberof XAPIContextInput
     */
    registration?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XAPIContextInput
     */
    platform?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XAPIContextInput
     */
    language?: string | null;
    /**
     * 
     * @type {XAPIActor}
     * @memberof XAPIContextInput
     */
    instructor?: XAPIActor | null;
    /**
     * 
     * @type {XAPIActor}
     * @memberof XAPIContextInput
     */
    team?: XAPIActor | null;
    /**
     * 
     * @type {object}
     * @memberof XAPIContextInput
     */
    contextActivities?: object | null;
    /**
     * 
     * @type {object}
     * @memberof XAPIContextInput
     */
    extensions?: object | null;
}

/**
 * Check if a given object implements the XAPIContextInput interface.
 */
export function instanceOfXAPIContextInput(value: object): value is XAPIContextInput {
    return true;
}

export function XAPIContextInputFromJSON(json: any): XAPIContextInput {
    return XAPIContextInputFromJSONTyped(json, false);
}

export function XAPIContextInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIContextInput {
    if (json == null) {
        return json;
    }
    return {
        
        'registration': json['registration'] == null ? undefined : json['registration'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'language': json['language'] == null ? undefined : json['language'],
        'instructor': json['instructor'] == null ? undefined : XAPIActorFromJSON(json['instructor']),
        'team': json['team'] == null ? undefined : XAPIActorFromJSON(json['team']),
        'contextActivities': json['context_activities'] == null ? undefined : json['context_activities'],
        'extensions': json['extensions'] == null ? undefined : json['extensions'],
    };
}

export function XAPIContextInputToJSON(json: any): XAPIContextInput {
    return XAPIContextInputToJSONTyped(json, false);
}

export function XAPIContextInputToJSONTyped(value?: XAPIContextInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'registration': value['registration'],
        'platform': value['platform'],
        'language': value['language'],
        'instructor': XAPIActorToJSON(value['instructor']),
        'team': XAPIActorToJSON(value['team']),
        'context_activities': value['contextActivities'],
        'extensions': value['extensions'],
    };
}

