/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XAPIResult } from './XAPIResult';
import {
    XAPIResultFromJSON,
    XAPIResultFromJSONTyped,
    XAPIResultToJSON,
    XAPIResultToJSONTyped,
} from './XAPIResult';
import type { XAPIActor } from './XAPIActor';
import {
    XAPIActorFromJSON,
    XAPIActorFromJSONTyped,
    XAPIActorToJSON,
    XAPIActorToJSONTyped,
} from './XAPIActor';
import type { XAPIVerb } from './XAPIVerb';
import {
    XAPIVerbFromJSON,
    XAPIVerbFromJSONTyped,
    XAPIVerbToJSON,
    XAPIVerbToJSONTyped,
} from './XAPIVerb';
import type { XAPIActivity } from './XAPIActivity';
import {
    XAPIActivityFromJSON,
    XAPIActivityFromJSONTyped,
    XAPIActivityToJSON,
    XAPIActivityToJSONTyped,
} from './XAPIActivity';
import type { XAPIContextOutput } from './XAPIContextOutput';
import {
    XAPIContextOutputFromJSON,
    XAPIContextOutputFromJSONTyped,
    XAPIContextOutputToJSON,
    XAPIContextOutputToJSONTyped,
} from './XAPIContextOutput';

/**
 * xAPI Statement response after storage.
 * @export
 * @interface XAPIStatementResponse
 */
export interface XAPIStatementResponse {
    /**
     * 
     * @type {XAPIActor}
     * @memberof XAPIStatementResponse
     */
    actor: XAPIActor;
    /**
     * 
     * @type {XAPIContextOutput}
     * @memberof XAPIStatementResponse
     */
    context?: XAPIContextOutput | null;
    /**
     * 
     * @type {string}
     * @memberof XAPIStatementResponse
     */
    id: string;
    /**
     * 
     * @type {XAPIActivity}
     * @memberof XAPIStatementResponse
     */
    object: XAPIActivity;
    /**
     * 
     * @type {XAPIResult}
     * @memberof XAPIStatementResponse
     */
    result?: XAPIResult | null;
    /**
     * 
     * @type {Date}
     * @memberof XAPIStatementResponse
     */
    stored: Date;
    /**
     * 
     * @type {Date}
     * @memberof XAPIStatementResponse
     */
    timestamp: Date;
    /**
     * 
     * @type {XAPIVerb}
     * @memberof XAPIStatementResponse
     */
    verb: XAPIVerb;
}

/**
 * Check if a given object implements the XAPIStatementResponse interface.
 */
export function instanceOfXAPIStatementResponse(value: object): value is XAPIStatementResponse {
    if (!('actor' in value) || value['actor'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('stored' in value) || value['stored'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('verb' in value) || value['verb'] === undefined) return false;
    return true;
}

export function XAPIStatementResponseFromJSON(json: any): XAPIStatementResponse {
    return XAPIStatementResponseFromJSONTyped(json, false);
}

export function XAPIStatementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIStatementResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'actor': XAPIActorFromJSON(json['actor']),
        'context': json['context'] == null ? undefined : XAPIContextOutputFromJSON(json['context']),
        'id': json['id'],
        'object': XAPIActivityFromJSON(json['object']),
        'result': json['result'] == null ? undefined : XAPIResultFromJSON(json['result']),
        'stored': (new Date(json['stored'])),
        'timestamp': (new Date(json['timestamp'])),
        'verb': XAPIVerbFromJSON(json['verb']),
    };
}

export function XAPIStatementResponseToJSON(json: any): XAPIStatementResponse {
    return XAPIStatementResponseToJSONTyped(json, false);
}

export function XAPIStatementResponseToJSONTyped(value?: XAPIStatementResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actor': XAPIActorToJSON(value['actor']),
        'context': XAPIContextOutputToJSON(value['context']),
        'id': value['id'],
        'object': XAPIActivityToJSON(value['object']),
        'result': XAPIResultToJSON(value['result']),
        'stored': value['stored'].toISOString(),
        'timestamp': value['timestamp'].toISOString(),
        'verb': XAPIVerbToJSON(value['verb']),
    };
}

