/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * xAPI Score - Quantitative result.
 * @export
 * @interface XAPIScore
 */
export interface XAPIScore {
    /**
     * 
     * @type {number}
     * @memberof XAPIScore
     */
    raw?: number | null;
    /**
     * 
     * @type {number}
     * @memberof XAPIScore
     */
    min?: number | null;
    /**
     * 
     * @type {number}
     * @memberof XAPIScore
     */
    max?: number | null;
    /**
     * 
     * @type {number}
     * @memberof XAPIScore
     */
    scaled?: number | null;
}

/**
 * Check if a given object implements the XAPIScore interface.
 */
export function instanceOfXAPIScore(value: object): value is XAPIScore {
    return true;
}

export function XAPIScoreFromJSON(json: any): XAPIScore {
    return XAPIScoreFromJSONTyped(json, false);
}

export function XAPIScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIScore {
    if (json == null) {
        return json;
    }
    return {
        
        'raw': json['raw'] == null ? undefined : json['raw'],
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
        'scaled': json['scaled'] == null ? undefined : json['scaled'],
    };
}

export function XAPIScoreToJSON(json: any): XAPIScore {
    return XAPIScoreToJSONTyped(json, false);
}

export function XAPIScoreToJSONTyped(value?: XAPIScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'raw': value['raw'],
        'min': value['min'],
        'max': value['max'],
        'scaled': value['scaled'],
    };
}

