/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XAPIContextInput } from './XAPIContextInput';
import {
    XAPIContextInputFromJSON,
    XAPIContextInputFromJSONTyped,
    XAPIContextInputToJSON,
    XAPIContextInputToJSONTyped,
} from './XAPIContextInput';
import type { XAPIResult } from './XAPIResult';
import {
    XAPIResultFromJSON,
    XAPIResultFromJSONTyped,
    XAPIResultToJSON,
    XAPIResultToJSONTyped,
} from './XAPIResult';
import type { XAPIActor } from './XAPIActor';
import {
    XAPIActorFromJSON,
    XAPIActorFromJSONTyped,
    XAPIActorToJSON,
    XAPIActorToJSONTyped,
} from './XAPIActor';
import type { XAPIVerb } from './XAPIVerb';
import {
    XAPIVerbFromJSON,
    XAPIVerbFromJSONTyped,
    XAPIVerbToJSON,
    XAPIVerbToJSONTyped,
} from './XAPIVerb';
import type { XAPIActivity } from './XAPIActivity';
import {
    XAPIActivityFromJSON,
    XAPIActivityFromJSONTyped,
    XAPIActivityToJSON,
    XAPIActivityToJSONTyped,
} from './XAPIActivity';

/**
 * xAPI Statement schema for receiving statements from game client.
 * Supports full xAPI 1.0 specification with game-specific context.
 * @export
 * @interface XAPIStatementCreate
 */
export interface XAPIStatementCreate {
    /**
     * Who performed the action
     * @type {XAPIActor}
     * @memberof XAPIStatementCreate
     */
    actor: XAPIActor;
    /**
     * 
     * @type {Array<object>}
     * @memberof XAPIStatementCreate
     */
    attachments?: Array<object> | null;
    /**
     * 
     * @type {XAPIActor}
     * @memberof XAPIStatementCreate
     */
    authority?: XAPIActor | null;
    /**
     * 
     * @type {XAPIContextInput}
     * @memberof XAPIStatementCreate
     */
    context?: XAPIContextInput | null;
    /**
     * 
     * @type {string}
     * @memberof XAPIStatementCreate
     */
    id?: string | null;
    /**
     * The object of the action
     * @type {XAPIActivity}
     * @memberof XAPIStatementCreate
     */
    object: XAPIActivity;
    /**
     * 
     * @type {XAPIResult}
     * @memberof XAPIStatementCreate
     */
    result?: XAPIResult | null;
    /**
     * 
     * @type {Date}
     * @memberof XAPIStatementCreate
     */
    stored?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof XAPIStatementCreate
     */
    timestamp?: Date | null;
    /**
     * The action performed
     * @type {XAPIVerb}
     * @memberof XAPIStatementCreate
     */
    verb: XAPIVerb;
    /**
     * 
     * @type {string}
     * @memberof XAPIStatementCreate
     */
    version?: string | null;
}

/**
 * Check if a given object implements the XAPIStatementCreate interface.
 */
export function instanceOfXAPIStatementCreate(value: object): value is XAPIStatementCreate {
    if (!('actor' in value) || value['actor'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('verb' in value) || value['verb'] === undefined) return false;
    return true;
}

export function XAPIStatementCreateFromJSON(json: any): XAPIStatementCreate {
    return XAPIStatementCreateFromJSONTyped(json, false);
}

export function XAPIStatementCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIStatementCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'actor': XAPIActorFromJSON(json['actor']),
        'attachments': json['attachments'] == null ? undefined : json['attachments'],
        'authority': json['authority'] == null ? undefined : XAPIActorFromJSON(json['authority']),
        'context': json['context'] == null ? undefined : XAPIContextInputFromJSON(json['context']),
        'id': json['id'] == null ? undefined : json['id'],
        'object': XAPIActivityFromJSON(json['object']),
        'result': json['result'] == null ? undefined : XAPIResultFromJSON(json['result']),
        'stored': json['stored'] == null ? undefined : (new Date(json['stored'])),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'verb': XAPIVerbFromJSON(json['verb']),
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function XAPIStatementCreateToJSON(json: any): XAPIStatementCreate {
    return XAPIStatementCreateToJSONTyped(json, false);
}

export function XAPIStatementCreateToJSONTyped(value?: XAPIStatementCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actor': XAPIActorToJSON(value['actor']),
        'attachments': value['attachments'],
        'authority': XAPIActorToJSON(value['authority']),
        'context': XAPIContextInputToJSON(value['context']),
        'id': value['id'],
        'object': XAPIActivityToJSON(value['object']),
        'result': XAPIResultToJSON(value['result']),
        'stored': value['stored'] == null ? value['stored'] : value['stored'].toISOString(),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'verb': XAPIVerbToJSON(value['verb']),
        'version': value['version'],
    };
}

