/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XAPIStatementResponse } from './XAPIStatementResponse';
import {
    XAPIStatementResponseFromJSON,
    XAPIStatementResponseFromJSONTyped,
    XAPIStatementResponseToJSON,
    XAPIStatementResponseToJSONTyped,
} from './XAPIStatementResponse';

/**
 * List of xAPI statements with pagination.
 * @export
 * @interface XAPIStatementListResponse
 */
export interface XAPIStatementListResponse {
    /**
     * 
     * @type {number}
     * @memberof XAPIStatementListResponse
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof XAPIStatementListResponse
     */
    skip: number;
    /**
     * 
     * @type {Array<XAPIStatementResponse>}
     * @memberof XAPIStatementListResponse
     */
    statements: Array<XAPIStatementResponse>;
    /**
     * 
     * @type {number}
     * @memberof XAPIStatementListResponse
     */
    total: number;
}

/**
 * Check if a given object implements the XAPIStatementListResponse interface.
 */
export function instanceOfXAPIStatementListResponse(value: object): value is XAPIStatementListResponse {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('skip' in value) || value['skip'] === undefined) return false;
    if (!('statements' in value) || value['statements'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function XAPIStatementListResponseFromJSON(json: any): XAPIStatementListResponse {
    return XAPIStatementListResponseFromJSONTyped(json, false);
}

export function XAPIStatementListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIStatementListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'skip': json['skip'],
        'statements': ((json['statements'] as Array<any>).map(XAPIStatementResponseFromJSON)),
        'total': json['total'],
    };
}

export function XAPIStatementListResponseToJSON(json: any): XAPIStatementListResponse {
    return XAPIStatementListResponseToJSONTyped(json, false);
}

export function XAPIStatementListResponseToJSONTyped(value?: XAPIStatementListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'skip': value['skip'],
        'statements': ((value['statements'] as Array<any>).map(XAPIStatementResponseToJSON)),
        'total': value['total'],
    };
}

