/* tslint:disable */
/* eslint-disable */
/**
 * Hello World Backend
 * Una API moderna y asíncrona para gestionar la plataforma de aprendizaje de programación con videjuegos
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jhonnyantonio892@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XAPIActorType } from './XAPIActorType';
import {
    XAPIActorTypeFromJSON,
    XAPIActorTypeFromJSONTyped,
    XAPIActorTypeToJSON,
    XAPIActorTypeToJSONTyped,
} from './XAPIActorType';

/**
 * xAPI Actor - Who performed the action.
 * @export
 * @interface XAPIActor
 */
export interface XAPIActor {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof XAPIActor
     */
    account?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof XAPIActor
     */
    mbox?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XAPIActor
     */
    mbox_sha1sum?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XAPIActor
     */
    name?: string | null;
    /**
     * 
     * @type {XAPIActorType}
     * @memberof XAPIActor
     */
    object_type?: XAPIActorType | null;
}



/**
 * Check if a given object implements the XAPIActor interface.
 */
export function instanceOfXAPIActor(value: object): value is XAPIActor {
    return true;
}

export function XAPIActorFromJSON(json: any): XAPIActor {
    return XAPIActorFromJSONTyped(json, false);
}

export function XAPIActorFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIActor {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : json['account'],
        'mbox': json['mbox'] == null ? undefined : json['mbox'],
        'mbox_sha1sum': json['mbox_sha1sum'] == null ? undefined : json['mbox_sha1sum'],
        'name': json['name'] == null ? undefined : json['name'],
        'object_type': json['object_type'] == null ? undefined : XAPIActorTypeFromJSON(json['object_type']),
    };
}

export function XAPIActorToJSON(json: any): XAPIActor {
    return XAPIActorToJSONTyped(json, false);
}

export function XAPIActorToJSONTyped(value?: XAPIActor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'mbox': value['mbox'],
        'mbox_sha1sum': value['mbox_sha1sum'],
        'name': value['name'],
        'object_type': XAPIActorTypeToJSON(value['object_type']),
    };
}

